#include "stdafx.h"
#include "..\spLb3\token.h"
#include "seman.h"
#include "..\spLb8\interpF.h"
union gnDat *_pd;
//_fop *_paddf=&_fadd;
struct recrdSMA	ftTbl[619]=	// таблиця припустимості типів для операцій
{{_if,_ui,32,_v,0,_v,0,"\n\tcmp\teax,0\n\tjz\t%s"},
{_if,_ui,32,_ui,32,_v,0,"\n\tcmp\teax,0\n\tjz\t%s"},
{_if,_ui,32,_si,32,_v,0,"\n\tcmp\teax,0\n\tjz\t%s"},
{_if,_ui,32,_f,32,_v,0,"\n\tcmp\teax,0\n\tjz\t%s"},
{_if,_ui,32,_d,64,_v,0,"\n\tcmp\teax,0\n\tjz\t%s"},
{_if,_si,32,_v,0,_v,0,"\n\tcmp\teax,0\n\tjz\t%s"},
{_if,_si,32,_ui,32,_v,0,"\n\tcmp\teax,0\n\tjz\t%s"},
{_if,_si,32,_si,32,_v,0,"\n\tcmp\teax,0\n\tjz\t%s"},
{_if,_si,32,_f,32,_v,0,"\n\tcmp\teax,0\n\tjz\t%s"},
{_if,_si,32,_d,64,_v,0,"\n\tcmp\teax,0\n\tjz\t%s"},
{_if,_f,32,_v,0,_v,0,"\n\tftst\n\tfstsw\tax\n\tsahf\n\tfincstp\n\tjz\t%s"},
{_if,_f,32,_ui,32,_v,0,"\n\tftst\n\tfstsw\tax\n\tsahf\n\tfincstp\n\tjz\t%s"},
{_if,_f,32,_si,32,_v,0,"\n\tftst\n\tfstsw\tax\n\tsahf\n\tfincstp\n\tjz\t%s"},
{_if,_f,32,_f,32,_v,0,"\n\tftst\n\tfstsw\tax\n\tsahf\n\tfincstp\n\tjz\t%s"},
{_if,_f,32,_d,64,_v,0,"\n\tftst\n\tfstsw\tax\n\tsahf\n\tfincstp\n\tjz\t%s"},
{_if,_d,64,_v,0,_v,0,"\n\tftst\n\tfstsw\tax\n\tsahf\n\tfincstp\n\tjz\t%s"},
{_if,_d,64,_ui,32,_v,0,"\n\tftst\n\tfstsw\tax\n\tsahf\n\tfincstp\n\tjz\t%s"},
{_if,_d,64,_si,32,_v,0,"\n\tftst\n\tfstsw\tax\n\tsahf\n\tfincstp\n\tjz\t%s"},
{_if,_d,64,_f,32,_v,0,"\n\tftst\n\tfstsw\tax\n\tsahf\n\tfincstp\n\tjz\t%s"},
{_if,_d,64,_d,64,_v,0,"\n\tftst\n\tfstsw\tax\n\tsahf\n\tfincstp\n\tjz\t%s"},
{_if,_ui+cdPtr,32,_v,0,_v,0,"\n\tcmp\teax,0\n\tjz\t%s"},
{_if,_ui+cdPtr,32,_ui,32,_v,0,"\n\tcmp\teax,0\n\tjz\t%s"},
{_if,_ui+cdPtr,32,_si,32,_v,0,"\n\tcmp\teax,0\n\tjz\t%s"},
{_if,_ui+cdPtr,32,_f,32,_v,0,"\n\tcmp\teax,0\n\tjz\t%s"},
{_if,_ui+cdPtr,32,_d,32,_v,0,"\n\tcmp\teax,0\n\tjz\t%s"},
{_if,_si+cdPtr,32,_v,0,_v,0,"\n\tcmp\teax,0\n\tjz\t%s"},
{_if,_si+cdPtr,32,_ui,32,_v,0,"\n\tcmp\teax,0\n\tjz\t%s"},
{_if,_si+cdPtr,32,_si,32,_v,0,"\n\tcmp\teax,0\n\tjz\t%s"},
{_if,_si+cdPtr,32,_f,32,_v,0,"\n\tcmp\teax,0\n\tjz\t%s"},
{_if,_si+cdPtr,32,_d,32,_v,0,"\n\tcmp\teax,0\n\tjz\t%s"},
{_if,_ui+cdPtr+cdArr,32,_v,0,_v,0,"\n\tcmp\teax,0\n\tjz\t%s"},
{_if,_ui+cdPtr+cdArr,32,_ui,32,_v,0,"\n\tcmp\teax,0\n\tjz\t%s"},
{_if,_ui+cdPtr+cdArr,32,_si,32,_v,0,"\n\tcmp\teax,0\n\tjz\t%s"},
{_if,_ui+cdPtr+cdArr,32,_f,32,_v,0,"\n\tcmp\teax,0\n\tjz\t%s"},
{_if,_ui+cdPtr+cdArr,32,_d,32,_v,0,"\n\tcmp\teax,0\n\tjz\t%s"},
{_if,_si+cdPtr+cdArr,32,_v,0,_v,0,"\n\tcmp\teax,0\n\tjz\t%s"},
{_if,_si+cdPtr+cdArr,32,_ui,32,_v,0,"\n\tcmp\teax,0\n\tjz\t%s"},
{_if,_si+cdPtr+cdArr,32,_si,32,_v,0,"\n\tcmp\teax,0\n\tjz\t%s"},
{_if,_si+cdPtr+cdArr,32,_f,32,_v,0,"\n\tcmp\teax,0\n\tjz\t%s"},
{_if,_si+cdPtr+cdArr,32,_d,32,_v,0,"\n\tcmp\teax,0\n\tjz\t%s"},
{_if,_f+cdPtr,32,_v,0,_v,0,"\n\tcmp\teax,0\n\tjz\t%s"},
{_if,_f+cdPtr,32,_ui,32,_v,0,"\n\tcmp\teax,0\n\tjz\t%s"},
{_if,_f+cdPtr,32,_si,32,_v,0,"\n\tcmp\teax,0\n\tjz\t%s"},
{_if,_f+cdPtr,32,_f,32,_v,0,"\n\tcmp\teax,0\n\tjz\t%s"},
{_if,_f+cdPtr,32,_d,64,_v,0,"\n\tcmp\teax,0\n\tjz\t%s"},
{_if,_d+cdPtr,64,_v,0,_v,0,"\n\tcmp\teax,0\n\tjz\t%s"},
{_if,_d+cdPtr,64,_ui,32,_v,0,"\n\tcmp\teax,0\n\tjz\t%s"},
{_if,_d+cdPtr,64,_si,32,_v,0,"\n\tcmp\teax,0\n\tjz\t%s"},
{_if,_d+cdPtr,64,_f,32,_v,0,"\n\tcmp\teax,0\n\tjz\t%s"},
{_if,_d+cdPtr,64,_d,64,_v,0,"\n\tcmp\teax,0\n\tjz\t%s"},
{_else,_v,0,_ui,32,_v,0,""},//"\n\tjmp\t%s"},
{_else,_v,0,_si,32,_v,0,""},//"\n\tjmp\t%s"},
{_else,_v,0,_f,32,_v,0,""},//"\n\tjmp\t%s"},
{_else,_v,0,_d,64,_v,0,""},//"\n\tjmp\t%s"},
{_break,_v,0,_v,0,_v,0,"\n\tjmp\t%s"},
{_whileP,_ui,32,_v,0,_v,0,"\n\tcmp\teax,0\n\tjz\t%s"},
{_whileP,_ui,32,_ui,32,_v,0,"\n\tcmp\teax,0\n\tjz\t%s"},
{_whileP,_ui,32,_si,32,_v,0,"\n\tcmp\teax,0\n\tjz\t%s"},
{_whileP,_ui,32,_f,32,_v,0,"\n\tcmp\teax,0\n\tjz\t%s"},
{_whileP,_ui,32,_d,64,_v,0,"\n\tcmp\teax,0\n\tjz\t%s"},
{_whileP,_si,32,_v,0,_v,0,"\n\tcmp\teax,0\n\tjz\t%s"},
{_whileP,_si,32,_ui,32,_v,0,"\n\tcmp\teax,0\n\tjz\t%s"},
{_whileP,_si,32,_si,32,_v,0,"\n\tcmp\teax,0\n\tjz\t%s"},
{_whileP,_si,32,_f,32,_v,0,"\n\tcmp\teax,0\n\tjz\t%s"},
{_whileP,_si,32,_d,64,_v,0,"\n\tcmp\teax,0\n\tjz\t%s"},
{_whileP,_f,32,_v,0,_v,0,"\n\tftst\n\tfstsw\tax\n\tsahf\n\tfincstp\n\tjz\t%s"},
{_whileP,_f,32,_ui,32,_v,0,"\n\tftst\n\tfstsw\tax\n\tsahf\n\tfincstp\n\tjz\t%s"},
{_whileP,_f,32,_si,32,_v,0,"\n\tftst\n\tfstsw\tax\n\tsahf\n\tfincstp\n\tjz\t%s"},
{_whileP,_f,32,_f,32,_v,0,"\n\tftst\n\tfstsw\tax\n\tsahf\n\tfincstp\n\tjz\t%s"},
{_whileP,_f,32,_d,64,_v,0,"\n\tftst\n\tfstsw\tax\n\tsahf\n\tfincstp\n\tjz\t%s"},
{_whileP,_d,64,_v,0,_v,0,"\n\tftst\n\tfstsw\tax\n\tsahf\n\tfincstp\n\tjz\t%s"},
{_whileP,_d,64,_ui,32,_v,0,"\n\tftst\n\tfstsw\tax\n\tsahf\n\tfincstp\n\tjz\t%s"},
{_whileP,_d,64,_si,32,_v,0,"\n\tftst\n\tfstsw\tax\n\tsahf\n\tfincstp\n\tjz\t%s"},
{_whileP,_d,64,_f,32,_v,0,"\n\tftst\n\tfstsw\tax\n\tsahf\n\tfincstp\n\tjz\t%s"},
{_whileP,_d,64,_d,64,_v,0,"\n\tftst\n\tfstsw\tax\n\tsahf\n\tfincstp\n\tjz\t%s"},
{_whileN,_v,0,_ui,32,_v,0,"\n\tcmp\teax,0\n\tjz\t%s\n%s:"},
{_whileN,_v,0,_si,32,_v,0,"\n\tcmp\teax,0\n\tjz\t%s\n%s:"},
{_whileN,_v,0,_f,32,_v,0,"\n\tftst\n\tfstsw\tax\n\tsahf\n\tfincstp\n\tjz\t%s\n%s:"},
{_whileN,_v,0,_d,64,_v,0,"\n\tftst\n\tfstsw\tax\n\tsahf\n\tfincstp\n\tjz\t%s\n%s:"},
{_whileN,_ui,32,_ui,32,_v,0,"\n\tcmp\teax,0\n\tjz\t%s\n%s:"},
{_whileN,_ui,32,_si,32,_v,0,"\n\tcmp\teax,0\n\tjz\t%s\n%s:"},
{_whileN,_ui,32,_f,32,_v,0,"\n\tftst\n\tfstsw\tax\n\tsahf\n\tfincstp\n\tjz\t%s\n%s:"},
{_whileN,_ui,32,_d,64,_v,0,"\n\tftst\n\tfstsw\tax\n\tsahf\n\tfincstp\n\tjz\t%s\n%s:"},
{_whileN,_si,32,_v,0,_v,0,"\n\tcmp\teax,0\n\tjz\t%s\n%s:"},
{_whileN,_si,32,_si,32,_v,0,"\n\tcmp\teax,0\n\tjz\t%s\n%s:"},
{_whileN,_si,32,_f,32,_v,0,"\n\tftst\n\tfstsw\tax\n\tsahf\n\tfincstp\n\tjz\t%s\n%s:"},
{_whileN,_si,32,_d,64,_v,0,"\n\tftst\n\tfstsw\tax\n\tsahf\n\tfincstp\n\tjz\t%s\n%s:"},
{_whileN,_f,32,_v,0,_v,0,"\n\tcmp\teax,0\n\tjz\t%s\n%s:"},
{_whileN,_f,32,_si,32,_v,0,"\n\tcmp\teax,0\n\tjz\t%s\n%s:"},
{_whileN,_f,32,_f,32,_v,0,"\n\tftst\n\tfstsw\tax\n\tsahf\n\tfincstp\n\tjz\t%s\n%s:"},
{_whileN,_f,32,_d,64,_v,0,"\n\tftst\n\tfstsw\tax\n\tsahf\n\tfincstp\n\tjz\t%s\n%s:"},
{_whileN,_d,64,_v,0,_v,0,"\n\tcmp\teax,0\n\tjz\t%s\n%s:"},
{_whileN,_d,64,_si,32,_v,0,"\n\tcmp\teax,0\n\tjz\t%s\n%s:"},
{_whileN,_d,64,_f,32,_v,0,"\n\tftst\n\tfstsw\tax\n\tsahf\n\tfincstp\n\tjz\t%s\n%s:"},
{_whileN,_d,64,_d,64,_v,0,"\n\tftst\n\tfstsw\tax\n\tsahf\n\tfincstp\n\tjz\t%s\n%s:"},
{_continue,_v,0,_v,0,_v,0,"\n\tjmp\t%s"},
{_for,_v,0,_v,0,_v,0,"\n\tjmp\t%s\n%s:"},
{_for,_v,0,_ui,32,_v,0,"\n\tjmp\t%s\n%s:"},
{_for,_v,0,_si,32,_v,0,"\n\tjmp\t%s\n%s:"},
{_for,_v,0,_f,32,_v,0,"\n\tjmp\t%s\n%s:"},
{_for,_v,0,_d,64,_v,0,"\n\tjmp\t%s\n%s:"},
{_cln,_ui,32,_ui,32,_ui,32,""},//"\n\tjmp\t%s"},
{_cln,_ui,32,_si,32,_si,32,""},//"\n\tjmp\t%s"},
{_cln,_ui,32,_f,32,_f,32,""},//"\n\tjmp\t%s"},
{_cln,_ui,32,_d,64,_d,64,""},//"\n\tjmp\t%s"},
{_cln,_si,32,_ui,32,_si,32,""},//"\n\tjmp\t%s"},
{_cln,_si,32,_si,32,_si,32,""},//"\n\tjmp\t%s"},
{_cln,_si,32,_f,32,_f,32,""},//"\n\tjmp\t%s"},
{_cln,_si,32,_d,64,_d,64,""},//"\n\tjmp\t%s"},
{_cln,_f,32,_ui,32,_f,32,""},//"\n\tjmp\t%s"},
{_cln,_f,32,_si,32,_f,32,""},//"\n\tjmp\t%s"},
{_cln,_f,32,_f,32,_f,32,""},//"\n\tjmp\t%s"},
{_cln,_f,32,_d,64,_d,64,""},//"\n\tjmp\t%s"},
{_cln,_d,64,_ui,32,_d,64,""},//"\n\tjmp\t%s"},
{_cln,_d,64,_si,32,_d,64,""},//"\n\tjmp\t%s"},
{_cln,_d,64,_f,32,_d,64,""},//"\n\tjmp\t%s"},
{_cln,_d,64,_d,64,_d,64,""},//"\n\tjmp\t%s"},
{_qmrk,_ui,32,_ui,32,_ui,32,"\n\tcmp\teax,0\n\tjz\t%s"},
{_qmrk,_ui,32,_si,32,_si,32,"\n\tcmp\teax,0\n\tjz\t%s"},
{_qmrk,_ui,32,_f,32,_f,32,"\n\tcmp\teax,0\n\tjz\t%s"},
{_qmrk,_ui,32,_d,64,_d,64,"\n\tcmp\teax,0\n\tjz\t%s"},
{_qmrk,_si,32,_ui,32,_ui,32,"\n\tcmp\teax,0\n\tjz\t%s"},
{_qmrk,_si,32,_si,32,_si,32,"\n\tcmp\teax,0\n\tjz\t%s"},
{_qmrk,_si,32,_f,32,_f,32,"\n\tcmp\teax,0\n\tjz\t%s"},
{_qmrk,_si,32,_d,64,_d,64,"\n\tcmp\teax,0\n\tjz\t%s"},
{_qmrk,_f,32,_ui,32,_ui,32,"\n\tftst\n\tfstsw\tax\n\tsahf\n\tfincstp\n\tjz\t%s"},
{_qmrk,_f,32,_si,32,_si,32,"\n\tftst\n\tfstsw\tax\n\tsahf\n\tfincstp\n\tjz\t%s"},
{_qmrk,_f,32,_f,32,_f,32,"\n\tftst\n\tfstsw\tax\n\tsahf\n\tfincstp\n\tjz\t%s"},
{_qmrk,_f,32,_d,64,_d,64,"\n\tftst\n\tfstsw\tax\n\tsahf\n\tfincstp\n\tjz\t%s"},
{_qmrk,_d,64,_ui,32,_ui,32,"\n\tftst\n\tfstsw\tax\n\tsahf\n\tfincstp\n\tjz\t%s"},
{_qmrk,_d,64,_si,32,_si,32,"\n\tftst\n\tfstsw\tax\n\tsahf\n\tfincstp\n\tjz\t%s"},
{_qmrk,_d,64,_f,32,_f,32,"\n\tftst\n\tfstsw\tax\n\tsahf\n\tfincstp\n\tjz\t%s"},
{_qmrk,_d,64,_d,64,_d,64,"\n\tftst\n\tfstsw\tax\n\tsahf\n\tfincstp\n\tjz\t%s"},
{_asOr,_ui,32,_ui,32,_ui,32,"\n\tor\t%s,%s"},
{_asOr,_ui,32,_si,32,_ui,32,"\n\tor\t%s,%s"},
{_asOr,_si,32,_ui,32,_si,32,"\n\tor\t%s,%s"},
{_asOr,_si,32,_si,32,_si,32,"\n\tor\t%s,%s"},
{_asAnd,_ui,32,_ui,32,_ui,32,"\n\tand\t%s,%s"},
{_asAnd,_ui,32,_si,32,_ui,32,"\n\tand\t%s,%s"},
{_asAnd,_si,32,_ui,32,_si,32,"\n\tand\t%s,%s"},
{_asAnd,_si,32,_si,32,_si,32,"\n\tand\t%s,%s"},
{_asXor,_ui,32,_ui,32,_ui,32,"\n\txor\t%s,%s"},
{_asXor,_ui,32,_si,32,_ui,32,"\n\txor\t%s,%s"},
{_asXor,_si,32,_ui,32,_si,32,"\n\txor\t%s,%s"},
{_asXor,_si,32,_si,32,_si,32,"\n\txor\t%s,%s"},
{_asAdd,_ui,32,_ui,32,_ui,32,"\n\tadd\t%s,%s"},
{_asAdd,_ui,32,_si,32,_ui,32,"\n\tadd\t%s,%s"},
{_asAdd,_ui,32,_f,32,_ui,32,"\n\tfild\t%s\n\tfadd\t%s\n\tfistp\t%s"},
{_asAdd,_ui,32,_d,32,_ui,32,"\n\tfild\t%s\n\tfadd\t%s\n\tfistp\t%s"},
{_asAdd,_si,32,_ui,32,_si,32,"\n\tadd\t%s,%s"},
{_asAdd,_si,32,_si,32,_si,32,"\n\tadd\t%s,%s"},
{_asAdd,_si,32,_f,32,_si,32,"\n\tfild\t%s\n\tfadd\t%s\n\tfistp\t%s"},
{_asAdd,_si,32,_d,32,_si,32,"\n\tfild\t%s\n\tfadd\t%s\n\tfistp\t%s"},
{_asAdd,_f,32,_ui,32,_f,32,"\n\tfld\t%s\n\tfiadd\t%s\n\tfstp\t%s"},
{_asAdd,_f,32,_si,32,_f,32,"\n\tfld\t%s\n\tfiadd\t%s\n\tfstp\t%s"},
{_asAdd,_f,32,_f,32,_f,32,"\n\tfld\t%s\n\tfadd\t%s\n\tfstp\t%s"},
{_asAdd,_f,32,_d,64,_f,32,"\n\tfld\t%s\n\tfadd\t%s\n\tfstp\t%s"},
{_asAdd,_d,64,_ui,32,_d,32,"\n\tfld\t%s\n\tfiadd\t%s\n\tfstp\t%s"},
{_asAdd,_d,64,_si,32,_d,64,"\n\tfld\t%s\n\tfiadd\t%s\n\tfstp\t%s"},
{_asAdd,_d,64,_f,32,_d,64,"\n\tfld\t%s\n\tfadd\t%s\n\tfstp\t%s"},
{_asAdd,_d,64,_d,64,_d,64,"\n\tfld\t%s\n\tfadd\t%s\n\tfstp\t%s"},
{_asAdd,_ui+cdPtr,32,_ui,32,_ui+cdPtr,32,"\n\tmov\tedi,%s\n\tmov\tcl,2\n\tshl\teax,cl\n\tadd\t[edi],eax"},
{_asAdd,_ui+cdPtr,32,_si,32,_ui+cdPtr,32,"\n\tmov\tedi,%s\n\tmov\tcl,2\n\tshl\teax,cl\n\tadd\t[edi],eax"},
{_asAdd,_si+cdPtr,32,_ui,32,_si+cdPtr,32,"\n\tmov\tedi,%s\n\tmov\tcl,2\n\tshl\teax,cl\n\tadd\t[edi],eax"},
{_asAdd,_si+cdPtr,32,_si,32,_si+cdPtr,32,"\n\tmov\tedi,%s\n\tmov\tcl,2\n\tshl\teax,cl\n\tadd\t[edi],eax"},
{_asAdd,_f+cdPtr,32,_ui,32,_f+cdPtr,32,"\n\tmov\tedi,%s\n\tmov\tcl,2\n\tshl\teax,cl\n\tadd\t[edi],eax"},
{_asAdd,_f+cdPtr,32,_si,32,_f+cdPtr,32,"\n\tmov\tedi,%s\n\tmov\tcl,2\n\tshl\teax,cl\n\tadd\t[edi],eax"},
{_asAdd,_d+cdPtr,32,_ui,32,_d+cdPtr,32,"\n\tmov\tedi,%s\n\tmov\tcl,3\n\tshl\teax,cl\n\tadd\t[edi],eax"},
{_asAdd,_d+cdPtr,32,_si,32,_d+cdPtr,32,"\n\tmov\tedi,%s\n\tmov\tcl,3\n\tshl\teax,cl\n\tadd\t[edi],eax"},
{_asSub,_ui,32,_ui,32,_ui,32,"\n\tsub\t%s,%s"},
{_asSub,_ui,32,_si,32,_ui,32,"\n\tsub\t%s,%s"},
{_asSub,_ui,32,_f,32,_ui,32,"\n\tfild\t%s\n\tfsub\t%s\n\tfistp\t%s"},
{_asSub,_ui,32,_d,32,_ui,32,"\n\tfild\t%s\n\tfsub\t%s\n\tfistp\t%s"},
{_asSub,_si,32,_ui,32,_si,32,"\n\tsub\t%s,%s"},
{_asSub,_si,32,_si,32,_si,32,"\n\tsub\t%s,%s"},
{_asSub,_si,32,_f,32,_si,32,"\n\tfild\t%s\n\tfsub\t%s\n\tfistp\t%s"},
{_asSub,_si,32,_d,32,_si,32,"\n\tfild\t%s\n\tfsub\t%s\n\tfistp\t%s"},
{_asSub,_f,32,_ui,32,_f,32,"\n\tfld\t%s\n\tfisub\t%s\n\tfstp\t%s"},
{_asSub,_f,32,_si,32,_f,32,"\n\tfld\t%s\n\tfisub\t%s\n\tfstp\t%s"},
{_asSub,_f,32,_f,32,_f,32,"\n\tfld\t%s\n\tfsub\t%s\n\tfstp\t%s"},
{_asSub,_f,32,_d,64,_f,32,"\n\tfld\t%s\n\tfsub\t%s\n\tfstp\t%s"},
{_asSub,_d,64,_ui,32,_d,32,"\n\tfld\t%s\n\tfisub\t%s\n\tfstp\t%s"},
{_asSub,_d,64,_si,32,_d,64,"\n\tfld\t%s\n\tfisub\t%s\n\tfstp\t%s"},
{_asSub,_d,64,_f,32,_d,64,"\n\tfld\t%s\n\tfsub\t%s\n\tfstp\t%s"},
{_asSub,_d,64,_d,64,_d,64,"\n\tfld\t%s\n\tfsub\t%s\n\tfstp\t%s"},
{_asSub,_ui+cdPtr,32,_ui,32,_ui+cdPtr,32,"\n\tmov\tedi,%s\n\tmov\tcl,2\n\tshl\teax,cl\n\tsub\t[edi],eax"},
{_asSub,_ui+cdPtr,32,_si,32,_ui+cdPtr,32,"\n\tmov\tedi,%s\n\tmov\tcl,2\n\tshl\teax,cl\n\tsub\t[edi],eax"},
{_asSub,_si+cdPtr,32,_ui,32,_si+cdPtr,32,"\n\tmov\tedi,%s\n\tmov\tcl,2\n\tshl\teax,cl\n\tsub\t[edi],eax"},
{_asSub,_si+cdPtr,32,_si,32,_si+cdPtr,32,"\n\tmov\tedi,%s\n\tmov\tcl,2\n\tshl\teax,cl\n\tsub\t[edi],eax"},
{_asSub,_f+cdPtr,32,_ui,32,_f+cdPtr,32,"\n\tmov\tedi,%s\n\tmov\tcl,2\n\tshl\teax,cl\n\tsub\t[edi],eax"},
{_asSub,_f+cdPtr,32,_si,32,_f+cdPtr,32,"\n\tmov\tedi,%s\n\tmov\tcl,2\n\tshl\teax,cl\n\tsub\t[edi],eax"},
{_asSub,_d+cdPtr,32,_ui,32,_d+cdPtr,32,"\n\tmov\tedi,%s\n\tmov\tcl,3\n\tshl\teax,cl\n\tsub\t[edi],eax"},
{_asSub,_d+cdPtr,32,_si,32,_d+cdPtr,32,"\n\tmov\tedi,%s\n\tmov\tcl,3\n\tshl\teax,cl\n\tsub\t[edi],eax"},
{_asMul,_ui,32,_ui,32,_ui,32,"\n\txchg\teax,%s\n\tmul\t%s\n\tmov\t%s,eax"},
{_asMul,_ui,32,_si,32,_ui,32,"\n\txchg\teax,%s\n\timul\t%s\n\tmov\t%s,eax"},
{_asMul,_ui,32,_f,32,_ui,32,"\n\tfild\t%s\n\tfmul\t%s\n\tfistp\t%s"},
{_asMul,_ui,32,_d,32,_ui,32,"\n\tfild\t%s\n\tfmul\t%s\n\tfistp\t%s"},
{_asMul,_si,32,_ui,32,_si,32,"\n\txchg\teax,%s\n\timul\t%s\n\tmov\t%s,eax"},
{_asMul,_si,32,_si,32,_si,32,"\n\txchg\teax,%s\n\timul\t%s\n\tmov\t%s,eax"},
{_asMul,_si,32,_f,32,_si,32,"\n\tfild\t%s\n\tfmul\t%s\n\tfistp\t%s"},
{_asMul,_si,32,_d,32,_si,32,"\n\tfild\t%s\n\tfmul\t%s\n\tfistp\t%s"},
{_asMul,_f,32,_ui,32,_f,32,"\n\tfld\t%s\n\tfimul\t%s\n\tfstp\t%s"},
{_asMul,_f,32,_si,32,_f,32,"\n\tfld\t%s\n\tfimul\t%s\n\tfstp\t%s"},
{_asMul,_f,32,_f,32,_f,32,"\n\tfld\t%s\n\tfmul\t%s\n\tfstp\t%s"},
{_asMul,_f,32,_d,64,_f,32,"\n\tfld\t%s\n\tfmul\t%s\n\tfstp\t%s"},
{_asMul,_d,64,_ui,32,_d,32,"\n\tfld\t%s\n\tfimul\t%s\n\tfstp\t%s"},
{_asMul,_d,64,_si,32,_d,64,"\n\tfld\t%s\n\tfimul\t%s\n\tfstp\t%s"},
{_asMul,_d,64,_f,32,_d,64,"\n\tfld\t%s\n\tfmul\t%s\n\tfstp\t%s"},
{_asMul,_d,64,_d,64,_d,64,"\n\tfld\t%s\n\tfmul\t%s\n\tfstp\t%s"},
{_asDiv,_ui,32,_ui,32,_ui,32,"\n\txchg\teax,%s\n\txor\tedx,edx\n\tdiv\t%s\n\tmov\t%s,eax"},
{_asDiv,_ui,32,_si,32,_ui,32,"\n\txchg\teax,%s\n\txor\tedx,edx\n\tidiv\t%s\n\tmov\t%s,eax"},
{_asDiv,_ui,32,_f,32,_ui,32,"\n\tfild\t%s\n\tfdiv\t%s\n\tfistp\t%s"},
{_asDiv,_ui,32,_d,32,_ui,32,"\n\tfild\t%s\n\tfdiv\t%s\n\tfistp\t%s"},
{_asDiv,_si,32,_ui,32,_si,32,"\n\txchg\teax,%s\n\txor\tedx,edx\n\ttest\teax,eax\n\tcmovl\tedx,__1\n\tidiv\t%s\n\tmov\t%s,eax"},
{_asDiv,_si,32,_si,32,_si,32,"\n\txchg\teax,%s\n\txor\tedx,edx\n\ttest\teax,eax\n\tcmovl\tedx,__1\n\tidiv\t%s\n\tmov\t%s,eax"},
{_asDiv,_si,32,_f,32,_si,32,"\n\tfild\t%s\n\tfdiv\t%s\n\tfistp\t%s"},
{_asDiv,_si,32,_d,32,_si,32,"\n\tfild\t%s\n\tfdiv\t%s\n\tfistp\t%s"},
{_asDiv,_f,32,_ui,32,_f,32,"\n\tfld\t%s\n\tfidiv\t%s\n\tfstp\t%s"},
{_asDiv,_f,32,_si,32,_f,32,"\n\tfld\t%s\n\tfidiv\t%s\n\tfstp\t%s"},
{_asDiv,_f,32,_f,32,_f,32,"\n\tfld\t%s\n\tfdiv\t%s\n\tfstp\t%s"},
{_asDiv,_f,32,_d,64,_f,32,"\n\tfld\t%s\n\tfdiv\t%s\n\tfstp\t%s"},
{_asDiv,_d,64,_ui,32,_d,32,"\n\tfld\t%s\n\tfidiv\t%s\n\tfstp\t%s"},
{_asDiv,_d,64,_si,32,_d,64,"\n\tfld\t%s\n\tfidiv\t%s\n\tfstp\t%s"},
{_asDiv,_d,64,_f,32,_d,64,"\n\tfld\t%s\n\tfdiv\t%s\n\tfstp\t%s"},
{_asDiv,_d,64,_d,64,_d,64,"\n\tfld\t%s\n\tfdiv\t%s\n\tfstp\t%s"},
{_asMod,_ui,32,_ui,32,_ui,32,"\n\txchg\teax,%s\n\tdiv\t%s\n\tmov\t%s,edx"},
{_asMod,_ui,32,_si,32,_ui,32,"\n\txchg\teax,%s\n\tidiv\t%s\n\tmov\t%s,edx"},
{_asMod,_si,32,_ui,32,_si,32,"\n\txchg\teax,%s\n\txor\tedx,edx\n\ttest\teax,eax\n\tcmovl\tedx,__1\n\tidiv\t%s\n\tmov\t%s,edx"},
{_asMod,_si,32,_si,32,_si,32,"\n\txchg\teax,%s\n\txor\tedx,edx\n\ttest\teax,eax\n\tcmovl\tedx,__1\n\tidiv\t%s\n\tmov\t%s,edx"},
{_asShr,_ui,32,_ui,32,_ui,32,"\n\tmov\teax,%s\n\tmov\tecx,%s\n\tshr\t%s,cl\n\tmov\t%s,eax"},
{_asShr,_ui,32,_si,32,_ui,32,"\n\tmov\teax,%s\n\tmov\tecx,%s\n\tshr\t%s,cl\n\tmov\t%s,eax"},
{_asShr,_si,32,_ui,32,_si,32,"\n\tmov\teax,%s\n\tmov\tecx,%s\n\tshr\t%s,cl\n\tmov\t%s,eax"},
{_asShr,_si,32,_si,32,_si,32,"\n\tmov\teax,%s\n\tmov\tecx,%s\n\tshr\t%s,cl\n\tmov\t%s,eax"},
{_asShl,_ui,32,_ui,32,_ui,32,"\n\tmov\teax,%s\n\tmov\tecx,%s\n\tshl\t%s,cl\n\tmov\t%s,eax"},
{_asShl,_ui,32,_si,32,_ui,32,"\n\tmov\teax,%s\n\tmov\tecx,%s\n\tshl\t%s,cl\n\tmov\t%s,eax"},
{_asShl,_si,32,_ui,32,_si,32,"\n\tmov\teax,%s\n\tmov\tecx,%s\n\tshl\t%s,cl\n\tmov\t%s,eax"},
{_asShl,_si,32,_si,32,_si,32,"\n\tmov\teax,%s\n\tmov\tecx,%s\n\tshl\t%s,cl\n\tmov\t%s,eax"},
{_ass,_ui,32,_ui,32,_ui,32,"\n\tmov\t%s,%s"},
{_ass,_ui,32,_si,32,_ui,32,"\n\tmov\t%s,%s"},
{_ass,_ui,32,_f,32,_ui,32,"\n\tfistp\t%s"},
{_ass,_ui,32,_d,32,_ui,32,"\n\tfistp\t%s"},
{_ass,_si,32,_ui,32,_si,32,"\n\tmov\t%s,%s"},
{_ass,_si,32,_si,32,_si,32,"\n\tmov\t%s,%s"},
{_ass,_si,32,_f,32,_si,32,"\n\tfistp\t%s"},
{_ass,_si,32,_d,32,_si,32,"\n\tfistp\t%s"},
{_ass,_f,32,_ui,32,_f,32,"\n\tfstp\t%s"},
{_ass,_f,32,_si,32,_f,32,"\n\tfstp\t%s"},
{_ass,_f,32,_f,32,_f,32,"\n\tfstp\t%s"},
{_ass,_f,32,_d,64,_f,32,"\n\tfstp\t%s"},
{_ass,_d,64,_ui,32,_d,64,"\n\tfstp\t%s"},
{_ass,_d,64,_si,32,_d,64,"\n\tfstp%s"},
{_ass,_d,64,_f,32,_d,64,"\n\tfstp%s"},
{_ass,_d,64,_d,64,_d,64,"\n\tfstp%s"},
{_ass,_ui+cdPtr,32,_ui+cdPtr,32,_ui+cdPtr,32,"\n\tmov\t%s,%s"},
{_ass,_ui+cdPtr,32,_si+cdPtr,32,_ui+cdPtr,32,"\n\tmov\t%s,%s"},
{_ass,_si+cdPtr,32,_ui+cdPtr,32,_si+cdPtr,32,"\n\tmov\t%s,%s"},
{_ass,_si+cdPtr,32,_si+cdPtr,32,_si+cdPtr,32,"\n\tmov\t%s,%s"},
{_ass,_f+cdPtr,32,_ui+cdPtr,32,_f+cdPtr,32,"\n\tmov\t%s,%s"},
{_ass,_f+cdPtr,32,_si+cdPtr,32,_f+cdPtr,32,"\n\tmov\t%s,%s"},
{_ass,_d+cdPtr,32,_ui+cdPtr,32,_d+cdPtr,32,"\n\tmov\t%s,%s"},
{_ass,_d+cdPtr,32,_si+cdPtr,32,_d+cdPtr,32,"\n\tmov\t%s,%s"},
{_dcr,_v,0,_ui,32,_ui,32,"\n\tdec\t%s\n\tmov\teax,%s"},
{_dcr,_v,0,_si,32,_si,32,"\n\tdec\t%s\n\tmov\teax,%s"},
{_dcr,_v,0,_ui+cdPtr,32,_ui+cdPtr,32,"\n\tsub\t%s,4\n\tmov\teax,%s"},
{_dcr,_v,0,_si+cdPtr,32,_si+cdPtr,32,"\n\tsub\t%s,4\n\tmov\teax,%s"},
{_dcr,_v,0,_f+cdPtr,32,_f+cdPtr,32,"\n\tsub\t%s,4\n\tmov\teax,%s"},
{_dcr,_v,0,_d+cdPtr,32,_d+cdPtr,32,"\n\tsub\t%s,8\n\tmov\teax,%s"},
{_dcr,_ui,32,_v,0,_ui,32,"\n\tmov\teax,%s\n\tdec\t%s"},
{_dcr,_si,32,_v,0,_si,32,"\n\tmov\teax,%s\n\tdec\t%s"},
{_dcr,_ui+cdPtr,32,_v,0,_ui+cdPtr,32,"\n\tmov\teax,%s\n\tsub\t%s,4"},
{_dcr,_si+cdPtr,32,_v,0,_si+cdPtr,32,"\n\tmov\teax,%s\n\tsub\t%s,4"},
{_dcr,_f+cdPtr,32,_v,0,_f+cdPtr,32,"\n\tmov\teax,%s\n\tsub\t%s,4"},
{_dcr,_d+cdPtr,32,_v,0,_d+cdPtr,32,"\n\tmov\teax,%s\n\tsub\t%s,8"},
{_inr,_v,0,_ui,32,_ui,32,"\n\tinc\t%s\n\tmov\teax,%s"},
{_inr,_v,0,_si,32,_si,32,"\n\tinc\t%s\n\tmov\teax,%s"},
{_inr,_v,0,_ui+cdPtr,32,_ui+cdPtr,32,"\n\tadd\t%s,4\n\tmov\teax,%s"},
{_inr,_v,0,_si+cdPtr,32,_si+cdPtr,32,"\n\tadd\t%s,4\n\tmov\teax,%s"},
{_inr,_v,0,_f+cdPtr,32,_f+cdPtr,32,"\n\tadd\t%s,4\n\tmov\teax,%s"},
{_inr,_v,0,_d+cdPtr,32,_d+cdPtr,32,"\n\tadd\t%s,8\n\tmov\teax,%s"},
{_inr,_ui,32,_v,0,_ui,32,"\n\tmov\teax,%s\n\tinc\t%s"},
{_inr,_si,32,_v,0,_si,32,"\n\tmov\teax,%s\n\tinc\t%s"},
{_inr,_ui+cdPtr,32,_v,0,_ui+cdPtr,32,"\n\tmov\teax,%s\n\tadd\t%s,4"},
{_inr,_si+cdPtr,32,_v,0,_si+cdPtr,32,"\n\tmov\teax,%s\n\tadd\t%s,4"},
{_inr,_f+cdPtr,32,_v,0,_f+cdPtr,32,"\n\tmov\teax,%s\n\tadd\t%s,4"},
{_inr,_d+cdPtr,32,_v,0,_d+cdPtr,32,"\n\tmov\teax,%s\n\tadd\t%s,4"},
{_lt,_ui,32,_ui,32,_ui,32,"\n\tcmp\t%s%s\n\tsetb\tal\n\tmovsx\teax,al"},
{_lt,_ui,32,_si,32,_ui,32,"\n\tcmp\t%s%s\n\tsetl\tal\n\tmovsx\teax,al"},
{_lt,_ui,32,_f,32,_ui,32,"\n\tfcomp\t%s%s\n\tfstsw\tax\n\tsahf\n\tsetb\tal\n\tmovsx\teax,al"},
{_lt,_ui,32,_d,64,_ui,32,"\n\tfcomp\t%s%s\n\tfstsw\tax\n\tsahf\n\tsetb\tal\n\t\tmovsx\teax,al"},
{_lt,_si,32,_ui,32,_ui,32,"\n\tcmp\t%s%s\n\tsetl\tal\n\tmovsx\teax,al"},
{_lt,_si,32,_si,32,_ui,32,"\n\tcmp\t%s%s\n\tsetl\tal\n\tmovsx\teax,al"},
{_lt,_si,32,_f,32,_ui,32,"\n\tfcomp\t%s%s\n\tfstsw\tax\n\tsahf\n\tsetb\tal\n\tmovsx\teax,al"},
{_lt,_si,32,_d,64,_ui,32,"\n\tfcomp\t%s%s\n\tfstsw\tax\n\tsahf\n\tsetb\tal\n\tmovsx\teax,al"},
{_lt,_f,32,_ui,32,_ui,32,"\n\tficomp\t%s%s\n\tfstsw\tax\n\tsahf\n\tsetb\tal\n\tmovsx\teax,al"},
{_lt,_f,32,_si,32,_ui,32,"\n\tficomp\t%s%s\n\tfstsw\tax\n\tsahf\n\tsetb\tal\n\tmovsx\teax,al"},
{_lt,_f,32,_f,32,_ui,32,"\n\tfcomp\t%s%s\n\tfstsw\tax\n\tsahf\n\tsetb\tal\n\tmovsx\teax,al"},
{_lt,_f,32,_d,64,_ui,32,"\n\tfcomp\t%s%s\n\tfstsw\tax\n\tsahf\n\tsetb\tal\n\tmovsx\teax,al"},
{_lt,_d,64,_ui,32,_ui,32,"\n\tficomp\t%s%s\n\tfstsw\tax\n\tsahf\n\tsetb\tal\n\tmovsx\teax,al"},
{_lt,_d,64,_si,32,_ui,32,"\n\tficomp\t%s%s\n\tfstsw\tax\n\tsahf\n\tsetb\tal\n\tmovsx\teax,al"},
{_lt,_d,64,_f,32,_ui,32,"\n\tfcomp\t%s%s\n\tfstsw\tax\n\tsahf\n\tsetb\tal\n\tmovsx\teax,al"},
{_lt,_d,64,_d,64,_ui,32,"\n\tfcomp\t%s%s\n\tfstsw\tax\n\tsahf\n\tsetb\tal\n\tmovsx\teax,al"},
{_le,_ui,32,_ui,32,_ui,32,"\n\tcmp\t%s%s\n\tsetbe\tal\n\tmovsx\teax,al"},
{_le,_ui,32,_si,32,_ui,32,"\n\tcmp\t%s%s\n\tsetle\tal\n\tmovsx\teax,al"},
{_le,_ui,32,_f,32,_ui,32,"\n\tfcomp\t%s%s\n\tfstsw\tax\n\tsahf\n\tsetbe\tal\n\tmovsx\teax,al"},
{_le,_ui,32,_d,64,_ui,32,"\n\tfcomp\t%s%s\n\tfstsw\tax\n\tsahf\n\tsetbe\tal\n\t\tmovsx\teax,al"},
{_le,_si,32,_ui,32,_ui,32,"\n\tcmp\t%s%s\n\tsetle\tal\n\tmovsx\teax,al"},
{_le,_si,32,_si,32,_ui,32,"\n\tcmp\t%s%s\n\tsetle\tal\n\tmovsx\teax,al"},
{_le,_si,32,_f,32,_ui,32,"\n\tfcomp\t%s%s\n\tfstsw\tax\n\tsahf\n\tsetbe\tal\n\tmovsx\teax,al"},
{_le,_si,32,_d,64,_ui,32,"\n\tfcomp\t%s%s\n\tfstsw\tax\n\tsahf\n\tsetbe\tal\n\tmovsx\teax,al"},
{_le,_f,32,_ui,32,_ui,32,"\n\tficomp\t%s%s\n\tfstsw\tax\n\tsahf\n\tsetbe\tal\n\tmovsx\teax,al"},
{_le,_f,32,_si,32,_ui,32,"\n\tficomp\t%s%s\n\tfstsw\tax\n\tsahf\n\tsetbe\tal\n\tmovsx\teax,al"},
{_le,_f,32,_f,32,_ui,32,"\n\tfcomp\t%s%s\n\tfstsw\tax\n\tsahf\n\tsetbe\tal\n\tmovsx\teax,al"},
{_le,_f,32,_d,64,_ui,32,"\n\tfcomp\t%s%s\n\tfstsw\tax\n\tsahf\n\tsetbe\tal\n\tmovsx\teax,al"},
{_le,_d,32,_ui,32,_ui,32,"\n\tficomp\t%s%s\n\tfstsw\tax\n\tsahf\n\tsetbe\tal\n\tmovsx\teax,al"},
{_le,_d,32,_si,32,_ui,32,"\n\tficomp\t%s%s\n\tfstsw\tax\n\tsahf\n\tsetbe\tal\n\tmovsx\teax,al"},
{_le,_d,32,_f,32,_ui,32,"\n\tfcomp\t%s%s\n\tfstsw\tax\n\tsahf\n\tsetbe\tal\n\tmovsx\teax,al"},
{_le,_d,32,_d,64,_ui,32,"\n\tfcomp\t%s%s\n\tfstsw\tax\n\tsahf\n\tsetbe\tal\n\tmovsx\teax,al"},
{_eq,_ui,32,_ui,32,_ui,32,"\n\tcmp\t%s%s\n\tsete\tal\n\tmovsx\teax,al"},
{_eq,_ui,32,_si,32,_ui,32,"\n\tcmp\t%s%s\n\tsete\tal\n\tmovsx\teax,al"},
{_eq,_ui,32,_f,32,_ui,32,"\n\tfcomp\t%s%s\n\tfstsw\tax\n\tsahf\n\tsete\tal\n\tmovsx\teax,al"},
{_eq,_ui,32,_d,64,_ui,32,"\n\tfcomp\t%s%s\n\tfstsw\tax\n\tsahf\n\tsete\tal\n\t\tmovsx\teax,al"},
{_eq,_si,32,_ui,32,_ui,32,"\n\tcmp\t%s%s\n\tsete\tal\n\tmovsx\teax,al"},
{_eq,_si,32,_si,32,_ui,32,"\n\tcmp\t%s%s\n\tsete\tal\n\tmovsx\teax,al"},
{_eq,_si,32,_f,32,_ui,32,"\n\tfcomp\t%s%s\n\tfstsw\tax\n\tsahf\n\tsete\tal\n\tmovsx\teax,al"},
{_eq,_si,32,_d,64,_ui,32,"\n\tfcomp\t%s%s\n\tfstsw\tax\n\tsahf\n\tsete\tal\n\tmovsx\teax,al"},
{_eq,_f,32,_ui,32,_ui,32,"\n\tficomp\t%s%s\n\tfstsw\tax\n\tsahf\n\tsete\tal\n\tmovsx\teax,al"},
{_eq,_f,32,_si,32,_ui,32,"\n\tficomp\t%s%s\n\tfstsw\tax\n\tsahf\n\tsete\tal\n\tmovsx\teax,al"},
{_eq,_f,32,_f,32,_ui,32,"\n\tfcomp\t%s%s\n\tfstsw\tax\n\tsahf\n\tsete\tal\n\tmovsx\teax,al"},
{_eq,_f,32,_d,64,_ui,32,"\n\tfcomp\t%s%s\n\tfstsw\tax\n\tsahf\n\tsete\tal\n\tmovsx\teax,al"},
{_eq,_d,64,_ui,32,_ui,32,"\n\tficomp\t%s%s\n\tfstsw\tax\n\tsahf\n\tsete\tal\n\tmovsx\teax,al"},
{_eq,_d,64,_si,32,_ui,32,"\n\tficomp\t%s%s\n\tfstsw\tax\n\tsahf\n\tsete\tal\n\tmovsx\teax,al"},
{_eq,_d,64,_f,32,_ui,32,"\n\tfcomp\t%s%s\n\tfstsw\tax\n\tsahf\n\tsete\tal\n\tmovsx\teax,al"},
{_eq,_d,64,_d,64,_ui,32,"\n\tfcomp\t%s%s\n\tfstsw\tax\n\tsahf\n\tsete\tal\n\tmovsx\teax,al"},
{_ne,_ui,32,_ui,32,_ui,32,"\n\tcmp\t%s%s\n\tsetne\tal\n\tmovsx\teax,al"},
{_ne,_ui,32,_si,32,_ui,32,"\n\tcmp\t%s%s\n\tsetne\tal\n\tmovsx\teax,al"},
{_ne,_ui,32,_f,32,_ui,32,"\n\tfcom\t%s%s\n\tfstsw\tax\n\tsahf\n\tsetne\tal\n\tmovsx\teax,al"},
{_ne,_ui,32,_d,64,_ui,32,"\n\tfcom\t%s%s\n\tfstsw\tax\n\tsahf\n\tsetne\tal\n\t\tmovsx\teax,al"},
{_ne,_si,32,_ui,32,_ui,32,"\n\tcmp\t%s%s\n\tsetne\tal\n\tmovsx\teax,al"},
{_ne,_si,32,_si,32,_ui,32,"\n\tcmp\t%s%s\n\tsetne\tal\n\tmovsx\teax,al"},
{_ne,_si,32,_f,32,_ui,32,"\n\tfcomp\t%s%s\n\tfstsw\tax\n\tsahf\n\tsetne\tal\n\tmovsx\teax,al"},
{_ne,_si,32,_d,64,_ui,32,"\n\tfcomp\t%s%s\n\tfstsw\tax\n\tsahf\n\tsetne\tal\n\tmovsx\teax,al"},
{_ne,_f,32,_ui,32,_ui,32,"\n\tficomp\t%s%s\n\tfstsw\tax\n\tsahf\n\tsetne\tal\n\tmovsx\teax,al"},
{_ne,_f,32,_si,32,_ui,32,"\n\tficomp\t%s%s\n\tfstsw\tax\n\tsahf\n\tsetne\tal\n\tmovsx\teax,al"},
{_ne,_f,32,_f,32,_ui,32,"\n\tfcomp\t%s%s\n\tfstsw\tax\n\tsahf\n\tsetne\tal\n\tmovsx\teax,al"},
{_ne,_f,32,_d,64,_ui,32,"\n\tfcomp\t%s%s\n\tfstsw\tax\n\tsahf\n\tsetne\tal\n\tmovsx\teax,al"},
{_ne,_d,64,_ui,32,_ui,32,"\n\tficomp\t%s%s\n\tfstsw\tax\n\tsahf\n\tsetne\tal\n\tmovsx\teax,al"},
{_ne,_d,64,_si,32,_ui,32,"\n\tficomp\t%s%s\n\tfstsw\tax\n\tsahf\n\tsetne\tal\n\tmovsx\teax,al"},
{_ne,_d,64,_f,32,_ui,32,"\n\tfcomp\t%s%s\n\tfstsw\tax\n\tsahf\n\tsetne\tal\n\tmovsx\teax,al"},
{_ne,_d,64,_d,64,_ui,32,"\n\tfcomp\t%s%s\n\tfstsw\tax\n\tsahf\n\tsetne\tal\n\tmovsx\teax,al"},
{_ge,_ui,32,_ui,32,_ui,32,"\n\tcmp\t%s%s\n\tsetae\tal\n\tmovsx\teax,al"},
{_ge,_ui,32,_si,32,_ui,32,"\n\tcmp\t%s%s\n\tsetge\tal\n\tmovsx\teax,al"},
{_ge,_ui,32,_f,32,_ui,32,"\n\tfcomp\t%s%s\n\tfstsw\tax\n\tsahf\n\tsetae\tal\n\tmovsx\teax,al"},
{_ge,_ui,32,_d,64,_ui,32,"\n\tfcomp\t%s%s\n\tfstsw\tax\n\tsahf\n\tsetae\tal\n\t\tmovsx\teax,al"},
{_ge,_si,32,_ui,32,_ui,32,"\n\tcmp\t%s%s\n\tsetge\tal\n\tmovsx\teax,al"},
{_ge,_si,32,_si,32,_ui,32,"\n\tcmp\t%s%s\n\tsetge\tal\n\tmovsx\teax,al"},
{_ge,_si,32,_f,64,_ui,32,"\n\tfcomp\t%s%s\n\tfstsw\tax\n\tsahf\n\tsetae\tal\n\tmovsx\teax,al"},
{_ge,_si,32,_d,64,_ui,32,"\n\tfcomp\t%s%s\n\tfstsw\tax\n\tsahf\n\tsetae\tal\n\tmovsx\teax,al"},
{_ge,_f,32,_ui,32,_ui,32,"\n\tficomp\t%s%s\n\tfstsw\tax\n\tsahf\n\tsetae\tal\n\tmovsx\teax,al"},
{_ge,_f,32,_si,32,_ui,32,"\n\tficomp\t%s%s\n\tfstsw\tax\n\tsahf\n\tsetae\tal\n\tmovsx\teax,al"},
{_ge,_f,32,_f,32,_ui,32,"\n\tfcomp\t%s%s\n\tfstsw\tax\n\tsahf\n\tsetae\tal\n\tmovsx\teax,al"},
{_ge,_f,32,_d,64,_ui,32,"\n\tfcomp\t%s%s\n\tfstsw\tax\n\tsahf\n\tsetae\tal\n\tmovsx\teax,al"},
{_ge,_d,64,_ui,32,_ui,32,"\n\tficomp\t%s%s\n\tfstsw\tax\n\tsahf\n\tsetae\tal\n\tmovsx\teax,al"},
{_ge,_d,64,_si,32,_ui,32,"\n\tficomp\t%s%s\n\tfstsw\tax\n\tsahf\n\tsetae\tal\n\tmovsx\teax,al"},
{_ge,_d,64,_f,32,_ui,32,"\n\tfcomp\t%s%s\n\tfstsw\tax\n\tsahf\n\tsetae\tal\n\tmovsx\teax,al"},
{_ge,_d,64,_d,64,_ui,32,"\n\tfcomp\t%s%s\n\tfstsw\tax\n\tsahf\n\tsetae\tal\n\tmovsx\teax,al"},
{_gt,_ui,32,_ui,32,_ui,32,"\n\tcmp\t%s%s\n\tseta\tal\n\tmovsx\teax,al"},
{_gt,_ui,32,_si,32,_ui,32,"\n\tcmp\t%s%s\n\tsetg\tal\n\tmovsx\teax,al"},
{_gt,_ui,32,_f,32,_ui,32,"\n\tfcomp\t%s%s\n\tfstsw\tax\n\tsahf\n\tseta\tal\n\tmovsx\teax,al"},
{_gt,_ui,32,_d,64,_ui,32,"\n\tfcomp\t%s%s\n\tfstsw\tax\n\tsahf\n\tseta\tal\n\t\tmovsx\teax,al"},
{_gt,_si,32,_ui,32,_ui,32,"\n\tcmp\t%s%s\n\tsetg\tal\n\tmovsx\teax,al"},
{_gt,_si,32,_si,32,_ui,32,"\n\tcmp\t%s%s\n\tsetg\tal\n\tmovsx\teax,al"},
{_gt,_si,32,_f,32,_ui,32,"\n\tfcomp\t%s%s\n\tfstsw\tax\n\tsahf\n\tseta\tal\n\tmovsx\teax,al"},
{_gt,_si,32,_d,64,_ui,32,"\n\tfcomp\t%s%s\n\tfstsw\tax\n\tsahf\n\tseta\tal\n\tmovsx\teax,al"},
{_gt,_f,32,_ui,32,_ui,32,"\n\tficomp\t%s%s\n\tfstsw\tax\n\tsahf\n\tseta\tal\n\tmovsx\teax,al"},
{_gt,_f,32,_si,32,_ui,32,"\n\tficomp\t%s%s\n\tfstsw\tax\n\tsahf\n\tseta\tal\n\tmovsx\teax,al"},
{_gt,_f,32,_f,32,_ui,32,"\n\tfcomp\t%s%s\n\tfstsw\tax\n\tsahf\n\tseta\tal\n\tmovsx\teax,al"},
{_gt,_f,32,_d,64,_ui,32,"\n\tfcomp\t%s%s\n\tfstsw\tax\n\tsahf\n\tseta\tal\n\tmovsx\teax,al"},
{_gt,_d,64,_ui,32,_ui,32,"\n\tficomp\t%s%s\n\tfstsw\tax\n\tsahf\n\tseta\tal\n\tmovsx\teax,al"},
{_gt,_d,64,_si,32,_ui,32,"\n\tficomp\t%s%s\n\tfstsw\tax\n\tsahf\n\tseta\tal\n\tmovsx\teax,al"},
{_gt,_d,64,_f,32,_ui,32,"\n\tfcomp\t%s%s\n\tfstsw\tax\n\tsahf\n\tseta\tal\n\tmovsx\teax,al"},
{_gt,_d,64,_d,64,_ui,32,"\n\tfcomp\t%s%s\n\tfstsw\tax\n\tsahf\n\tseta\tal\n\tmovsx\teax,al"},
{_add,_ui,32,_ui,32,_ui,32,"\n\tadd\t%s%s"},//eax
{_add,_ui,32,_si,32,_si,32,"\n\tadd\t%s%s"},//eax
{_add,_ui,32,_f,32,_f,32,"\n\tfadd\t%s%s"},
{_add,_ui,32,_d,64,_d,64,"\n\tfadd\t%s%s"},
{_add,_ui,32,_ui+cdPtr,32,_ui+cdPtr,32,"\n\tmov\tcl,2\n\tshl\t%scl\n\tadd\teax,%s"},//eax
{_add,_ui,32,_si+cdPtr,32,_si+cdPtr,32,"\n\tmov\tcl,2\n\tshl\t%scl\n\tadd\teax,%s"},//eax
{_add,_ui,32,_f+cdPtr,32,_f+cdPtr,32,"\n\tmov\tcl,2\n\tshl\t%scl\n\tadd\teax,%s"},//eax
{_add,_ui,32,_d+cdPtr,32,_d+cdPtr,32,"\n\tmov\tcl,3\n\tshl\t%scl\n\tadd\teax,%s"},//eax
{_add,_ui,32,_ui+cdPtr+cdArr,32,_ui+cdPtr,32,"\n\tmov\tcl,2\n\tshl\t%scl\n\tlea\teax,%s[eax]"},//eax
{_add,_ui,32,_si+cdPtr+cdArr,32,_si+cdPtr,32,"\n\tmov\tcl,2\n\tshl\t%scl\n\tlea\teax,%s[eax]"},//eax
{_add,_ui,32,_f+cdPtr+cdArr,32,_f+cdPtr,32,"\n\tmov\tcl,2\n\tshl\t%scl\n\tlea\teax,%s[eax]"},//eax
{_add,_ui,32,_d+cdPtr+cdArr,32,_d+cdPtr,32,"\n\tmov\tcl,3\n\tshl\t%scl\n\tlea\teax,%s[eax]"},//eax
{_add,_si,32,_ui,32,_si,32,"\n\tadd\t%s%s"},//eax
{_add,_si,32,_si,32,_si,32,"\n\tadd\t%s%s"},//eax
{_add,_si,32,_f,32,_f,32,"\n\tfadd\t%s%s"},
{_add,_si,32,_d,64,_d,64,"\n\tfadd\t%s%s"},
{_add,_si,32,_ui+cdPtr,32,_ui+cdPtr,32,"\n\tmov\tcl,2\n\tshl\t%scl\n\tadd\teax,%s"},//eax
{_add,_si,32,_si+cdPtr,32,_si+cdPtr,32,"\n\tmov\tcl,2\n\tshl\t%scl\n\tadd\teax,%s"},//eax
{_add,_si,32,_f+cdPtr,32,_f+cdPtr,32,"\n\tmov\tcl,2\n\tshl\t%scl\n\tadd\teax,%s"},//eax
{_add,_si,32,_d+cdPtr,32,_d+cdPtr,32,"\n\tmov\tcl,3\n\tshl\t%scl\n\tadd\teax,%s"},//eax
{_add,_si,32,_ui+cdPtr+cdArr,32,_ui+cdPtr,32,"\n\tmov\tcl,2\n\tshl\t%scl\n\tlea\teax,%s[eax]"},//eax
{_add,_si,32,_si+cdPtr+cdArr,32,_si+cdPtr,32,"\n\tmov\tcl,2\n\tshl\t%scl\n\tlea\teax,%s[eax]"},//eax
{_add,_si,32,_f+cdPtr+cdArr,32,_f+cdPtr,32,"\n\tmov\tcl,2\n\tshl\t%scl\n\tlea\teax,%s[eax]"},//eax
{_add,_si,32,_d+cdPtr+cdArr,32,_d+cdPtr,32,"\n\tmov\tcl,3\n\tshl\t%scl\n\tlea\teax,%s[eax]"},//eax
{_add,_f,32,_ui,32,_f,32,"\n\tfiadd\t%s%s"},
{_add,_f,32,_si,32,_f,32,"\n\tfiadd\t%s%s"},
{_add,_f,32,_f,32,_f,32,"\n\tfadd\t%s%s"},
{_add,_f,32,_d,64,_d,64,"\n\tfadd\t%s%s"},
{_add,_d,64,_ui,32,_d,64,"\n\tfiadd\t%s%s"},
{_add,_d,64,_si,32,_d,64,"\n\tfiadd\t%s%s"},
{_add,_d,64,_f,32,_d,64,"\n\tfadd\t%s%s"},
{_add,_d,64,_d,64,_d,64,"\n\tfadd\t%s%s"},
{_add,_ui+cdPtr,32,_ui,32,_ui+cdPtr,32,"\n\tpush\teax\n\tmov\t%s%s\n\tmov\tcl,2\n\tshl\teax,cl\n\tadd\t[esp],eax\n\tpop\teax"},
{_add,_ui+cdPtr,32,_si,32,_ui+cdPtr,32,"\n\tpush\teax\n\tmov\t%s%s\n\tmov\tcl,2\n\tshl\teax,cl\n\tadd\t[esp],eax\n\tpop\teax"},
{_add,_si+cdPtr,32,_ui,32,_si+cdPtr,32,"\n\tpush\teax\n\tmov\t%s%s\n\tmov\tcl,2\n\tshl\teax,cl\n\tadd\t[esp],eax\n\tpop\teax"},
{_add,_si+cdPtr,32,_si,32,_si+cdPtr,32,"\n\tpush\teax\n\tmov\t%s%s\n\tmov\tcl,2\n\tshl\teax,cl\n\tadd\t[esp],eax\n\tpop\teax"},
{_add,_f+cdPtr,32,_ui,32,_f+cdPtr,32,"\n\tpush\teax\n\tmov\t%s%s\n\tmov\tcl,2\n\tshl\teax,cl\n\tadd\t[esp],eax\n\tpop\teax"},
{_add,_f+cdPtr,32,_si,32,_f+cdPtr,32,"\n\tpush\teax\n\tmov\t%s%s\n\tmov\tcl,2\n\tshl\teax,cl\n\tadd\t[esp],eax\n\tpop\teax"},
{_add,_d+cdPtr,32,_ui,32,_d+cdPtr,32,"\n\tpush\teax\n\tmov\t%s%s\n\tmov\tcl,3\n\tshl\teax,cl\n\tadd\t[esp],eax\n\tpop\teax"},
{_add,_d+cdPtr,32,_si,32,_d+cdPtr,32,"\n\tpush\teax%s\n\tmov\teax,8\n\tmul\t%s\n\tadd\t[esp],eax\n\tpop\teax"},
{_add,_ui+cdPtr+cdArr,32,_ui,32,_ui+cdPtr,32,"\n\tpush\teax\n\tmov\t%s%s\n\tmov\tcl,2\n\tshl\teax,cl\n\tadd\t[esp],eax\n\tpop\teax"},
{_add,_ui+cdPtr+cdArr,32,_si,32,_ui+cdPtr,32,"\n\tpush\teax\n\tmov\t%s%s\n\tmov\tcl,2\n\tshl\teax,cl\n\tadd\t[esp],eax\n\tpop\teax"},
{_add,_si+cdPtr+cdArr,32,_ui,32,_si+cdPtr,32,"\n\tpush\teax\n\tmov\t%s%s\n\tmov\tcl,2\n\tshl\teax,cl\n\tadd\t[esp],eax\n\tpop\teax"},
{_add,_si+cdPtr+cdArr,32,_si,32,_si+cdPtr,32,"\n\tpush\teax\n\tmov\t%s%s\n\tmov\tcl,2\n\tshl\teax,cl\n\tadd\t[esp],eax\n\tpop\teax"},
{_add,_f+cdPtr+cdArr,32,_ui,32,_f+cdPtr,32,"\n\tpush\teax\n\tmov\t%s%s\n\tmov\tcl,2\n\tshl\teax,cl\n\tadd\t[esp],eax\n\tpop\teax"},
{_add,_f+cdPtr+cdArr,32,_si,32,_f+cdPtr,32,"\n\tpush\teax\n\tmov\t%s%s\n\tmov\tcl,2\n\tshl\teax,cl\n\tadd\t[esp],eax\n\tpop\teax"},
{_add,_d+cdPtr+cdArr,64,_ui,32,_d+cdPtr,64,"\n\tpush\teax\n\tmov\t%s%s\n\tmov\tcl,3\n\tshl\teax,cl\n\tadd\t[esp],eax\n\tpop\teax"},
{_add,_d+cdPtr+cdArr,64,_si,32,_d+cdPtr,64,"\n\tpush\teax%s\n\tmov\teax,8\n\tmul\t%s\n\tadd\t[esp],eax\n\tpop\teax"},
{_sub,_ui,32,_ui,32,_ui,32,"\n\tsub\t%s%s"},//eax
{_sub,_ui,32,_si,32,_si,32,"\n\tsub\t%s%s"},//eax
{_sub,_ui,32,_f,32,_f,32,"\n\tfsub\t%s%s"},
{_sub,_ui,32,_d,64,_d,64,"\n\tfsub\t%s%s"},
{_sub,_si,32,_ui,32,_si,32,"\n\tsub\t%s%s"},//eax
{_sub,_si,32,_si,32,_si,32,"\n\tsub\t%s%s"},//eax
{_sub,_si,32,_f,32,_f,32,"\n\tfsub\t%s%s"},
{_sub,_si,32,_d,64,_d,64,"\n\tfsub\t%s%s"},
{_sub,_f,32,_ui,32,_f,32,"\n\tfisub\t%s%s"},
{_sub,_f,32,_si,32,_f,32,"\n\tfisub\t%s%s"},
{_sub,_f,32,_f,32,_f,32,"\n\tfsub\t%s%s"},
{_sub,_f,32,_d,64,_d,64,"\n\tfsub\t%s%s"},
{_sub,_d,64,_ui,32,_d,64,"\n\tfisub\t%s%s"},
{_sub,_d,64,_si,32,_d,64,"\n\tfisub\t%s%s"},
{_sub,_d,64,_f,32,_d,64,"\n\tfsub\t%s%s"},
{_sub,_d,64,_d,64,_d,64,"\n\tfsub\t%s%s"},
{_sub,_ui+cdPtr,32,_ui,32,_ui+cdPtr,32,"\n\tpush\teax\n\tmov\t%s%s\n\tmov\tcl,2\n\tshl\teax,cl\n\tsub\t[esp],eax\n\tpop\teax"},
{_sub,_ui+cdPtr,32,_si,32,_ui+cdPtr,32,"\n\tpush\teax\n\tmov\t%s%s\n\tmov\tcl,2\n\tshl\teax,cl\n\tsub\t[esp],eax\n\tpop\teax"},
{_sub,_ui+cdPtr,32,_ui+cdPtr,32,_si,32,"\n\tsub\t%s%s\n\tmov\tcl,2\n\tshr\teax,cl"},
{_sub,_si+cdPtr,32,_ui,32,_si+cdPtr,32,"\n\tpush\teax\n\tmov\t%s%s\n\tmov\tcl,2\n\tshl\teax,cl\n\tsub\t[esp],eax\n\tpop\teax"},
{_sub,_si+cdPtr,32,_si,32,_si+cdPtr,32,"\n\tpush\teax\n\tmov\t%s%s\n\tmov\tcl,2\n\tshl\teax,cl\n\tsub\t[esp],eax\n\tpop\teax"},
{_sub,_si+cdPtr,32,_si+cdPtr,32,_si,32,"\n\tsub\t%s%s\n\tmov\tcl,2\n\tshr\teax,cl"},
{_sub,_f+cdPtr,32,_ui,32,_f+cdPtr,32,"\n\tpush\teax\n\tmov\t%s%s\n\tmov\tcl,2\n\tshl\teax,cl\n\tsub\t[esp],eax\n\tpop\teax"},
{_sub,_f+cdPtr,32,_si,32,_f+cdPtr,32,"\n\tpush\teax\n\tmov\t%s%s\n\tmov\tcl,2\n\tshl\teax,cl\n\tsub\t[esp],eax\n\tpop\teax"},
{_sub,_f+cdPtr,32,_f+cdPtr,32,_si,32,"\n\tsub\t%s%s\n\tmov\tcl,2\n\tshr\teax,cl"},
{_sub,_d+cdPtr,64,_ui,32,_d+cdPtr,64,"\n\tpush\teax\n\tmov\t%s%s\n\tmov\tcl,3\n\tshl\teax,cl\n\tsub\t[esp],eax\n\tpop\teax"},
{_sub,_d+cdPtr,64,_si,32,_d+cdPtr,64,"\n\tpush\teax%s\n\tmov\teax,8\n\tmul\t%s\n\tsub\t[esp],eax\n\tpop\teax"},
{_sub,_d+cdPtr,64,_d+cdPtr,64,_si,32,"\n\tsub\t%s%s\n\tmov\tcl,3\n\tshr\teax,cl"},
{_sub,_ui+cdPtr+cdArr,32,_ui,32,_ui+cdPtr,32,"\n\tpush\teax\n\tmov\t%s%s\n\tmov\tcl,2\n\tshl\teax,cl\n\tsub\t[esp],eax\n\tpop\teax"},
{_sub,_ui+cdPtr+cdArr,32,_si,32,_ui+cdPtr,32,"\n\tpush\teax\n\tmov\t%s%s\n\tmov\tcl,2\n\tshl\teax,cl\n\tsub\t[esp],eax\n\tpop\teax"},
{_sub,_ui+cdPtr+cdArr,32,_ui+cdPtr,32,_si,32,"\n\tsub\t%s%s\n\tmov\tcl,2\n\tshr\teax,cl"},
{_sub,_si+cdPtr+cdArr,32,_ui,32,_si+cdPtr,32,"\n\tpush\teax\n\tmov\t%s%s\n\tmov\tcl,2\n\tshl\teax,cl\n\tsub\t[esp],eax\n\tpop\teax"},
{_sub,_si+cdPtr+cdArr,32,_si,32,_si+cdPtr,32,"\n\tpush\teax\n\tmov\t%s%s\n\tmov\tcl,2\n\tshl\teax,cl\n\tsub\t[esp],eax\n\tpop\teax"},
{_sub,_si+cdPtr+cdArr,32,_si+cdPtr,32,_si,32,"\n\tsub\t%s%s\n\tmov\tcl,2\n\tshr\teax,cl"},
{_sub,_f+cdPtr+cdArr,32,_ui,32,_f+cdPtr,32,"\n\tpush\teax\n\tmov\t%s%s\n\tmov\tcl,2\n\tshl\teax,cl\n\tsub\t[esp],eax\n\tpop\teax"},
{_sub,_f+cdPtr+cdArr,32,_si,32,_f+cdPtr,32,"\n\tpush\teax\n\tmov\t%s%s\n\tmov\tcl,2\n\tshl\teax,cl\n\tsub\t[esp],eax\n\tpop\teax"},
{_sub,_f+cdPtr+cdArr,32,_f+cdPtr,32,_si,32,"\n\tsub\t%s%s\n\tmov\tcl,2\n\tshr\teax,cl"},
{_sub,_d+cdPtr+cdArr,32,_ui,32,_d+cdPtr,32,"\n\tpush\teax\n\tmov\t%s%s\n\tmov\tcl,3\n\tshl\teax,cl\n\tsub\t[esp],eax\n\tpop\teax"},
{_sub,_d+cdPtr+cdArr,32,_si,32,_d+cdPtr,32,"\n\tpush\teax%s\n\tmov\teax,8\n\tmul\t%s\n\tsub\t[esp],eax\n\tpop\teax"},
{_sub,_d+cdPtr+cdArr,32,_d+cdPtr,32,_si,32,"\n\tsub\t%s%s\n\tmov\tcl,3\n\tshr\teax,cl"},
{_mul,_v,0,_ui+cdPtr,32,_ui,32,"\n\tmov\tesi,%s%s\n\tmov\teax,[esi]"},
{_mul,_v,0,_si+cdPtr,32,_si,32,"\n\tmov\tesi,%s%s\n\tmov\teax,[esi]"},
{_mul,_v,0,_f+cdPtr,32,_f,32,"\n\tmov\tesi%s%s\n\tfld\tdword ptr[eax]"},
{_mul,_v,0,_d+cdPtr,32,_d,64,"\n\tmov\tesi%s%s\n\tfld\tqword ptr[eax]"},
{_mul,_v,0,_ui+cdPtr+cdArr,32,_ui,32,"\n\tlea\tesi,%s%s\n\tmov\teax,[esi]"},
{_mul,_v,0,_si+cdPtr+cdArr,32,_si,32,"\n\tlea\tesi,%s%s\n\tmov\teax,[esi]"},
{_mul,_v,0,_f+cdPtr+cdArr,32,_f,32,"\n\tlea\tesi%s%s\n\tfld\tdword ptr[eax]"},
{_mul,_v,0,_d+cdPtr+cdArr,32,_d,64,"\n\tlea\tesi%s%s\n\tfld\tqword ptr[eax]"},
{_mul,_ui,32,_ui,32,_ui,32,"\n\tmul\t%s%s"},//eax
{_mul,_ui,32,_si,32,_si,32,"\n\timul\t%s%s"},//eax
{_mul,_ui,32,_f,32,_f,32,"\n\tfmul\t%s%s"},
{_mul,_ui,32,_d,64,_d,64,"\n\tfmul\t%s%s"},
{_mul,_si,32,_ui,32,_si,32,"\n\timul\t%s%s"},//eax
{_mul,_si,32,_si,32,_si,32,"\n\timul\t%s%s"},//eax
{_mul,_si,32,_f,32,_f,32,"\n\tfmul\t%s%s"},
{_mul,_si,32,_d,64,_d,64,"\n\tfmul\t%s%s"},
{_mul,_f,32,_ui,32,_f,32,"\n\tfimul\t%s%s"},
{_mul,_f,32,_si,32,_f,32,"\n\tfimul\t%s%s"},
{_mul,_f,32,_f,32,_f,32,"\n\tfmul\t%s%s"},
{_mul,_f,32,_d,64,_d,64,"\n\tfmul\t%s%s"},
{_mul,_d,64,_ui,32,_d,64,"\n\tfimul\t%s%s"},
{_mul,_d,64,_si,32,_d,64,"\n\tfimul\t%s%s"},
{_mul,_d,64,_f,32,_d,64,"\n\tfmul\t%s%s"},
{_mul,_d,64,_d,64,_d,64,"\n\tfmul\t%s%s"},
{_div,_ui,32,_ui,32,_ui,32,"\n\txor\tedx,edx\n\tdiv\t%s%s"},//eax
{_div,_ui,32,_si,32,_si,32,"\n\txor\tedx,edx\n\tidiv\t%s%s"},//eax
{_div,_ui,32,_f,32,_f,32,"\n\tfdiv\t%s%s"},
{_div,_ui,32,_d,64,_d,64,"\n\tfdiv\t%s%s"},
{_div,_si,32,_ui,32,_si,32,"\n\txor\tedx,edx\n\ttest\teax,eax\n\tcmovl\tedx,__1\n\tidiv\t%s%s"},//eax
{_div,_si,32,_si,32,_si,32,"\n\txor\tedx,edx\n\ttest\teax,eax\n\tcmovl\tedx,__1\n\tidiv\t%s%s"},//eax
{_div,_si,32,_f,32,_f,32,"\n\tfdiv\t%s%s"},
{_div,_si,32,_d,64,_d,64,"\n\tfdiv\t%s%s"},
{_div,_f,32,_ui,32,_f,32,"\n\tfidiv\t%s%s"},
{_div,_f,32,_si,32,_f,32,"\n\tfidiv\t%s%s"},
{_div,_f,32,_f,32,_f,32,"\n\tfdiv\t%s%s"},
{_div,_f,32,_d,64,_d,64,"\n\tfdiv\t%s%s"},
{_div,_d,64,_ui,32,_d,64,"\n\tfidiv\t%s%s"},
{_div,_d,64,_si,32,_d,64,"\n\tfidiv\t%s%s"},
{_div,_d,64,_f,32,_d,64,"\n\tfdiv\t%s%s"},
{_div,_d,64,_d,64,_d,64,"\n\tfdiv\t%s%s"},
{_mod,_ui,32,_ui,32,_ui,32,"\n\txor\tedx,edx\n\tdiv\t%s%s\n\tmov\teax,edx"},//eax
{_mod,_ui,32,_si,32,_si,32,"\n\txor\tedx,edx\n\tidiv\t%s%s\n\tmov\teax,edx"},//eax
{_mod,_si,32,_ui,32,_si,32,"\n\txor\tedx,edx\n\ttest\teax,eax\n\tcmovl\tedx,__1\n\tidiv\t%s%s\n\tmov\teax,edx"},//eax
{_mod,_si,32,_si,32,_si,32,"\n\txor\tedx,edx\n\ttest\teax,eax\n\tcmovl\tedx,__1\n\tidiv\t%s%s\n\tmov\teax,edx"},//eax
{_orB,_ui,32,_ui,32,_ui,32,"\n\tor\t%s%s"},
{_orB,_ui,32,_si,32,_si,32,"\n\tor\t%s%s"},
{_orB,_si,32,_ui,32,_si,32,"\n\tor\t%s%s"},
{_orB,_si,32,_si,32,_si,32,"\n\tor\t%s%s"},
{_andB,_ui,32,_ui,32,_ui,32,"\n\tand\t%s%s"},
{_andB,_ui,32,_si,32,_si,32,"\n\tand\t%s%s"},
{_andB,_si,32,_ui,32,_si,32,"\n\tand\t%s%s"},
{_andB,_si,32,_si,32,_si,32,"\n\tand\t%s%s"},
{_xorB,_ui,32,_ui,32,_ui,32,"\n\txor\t%s%s"},
{_xorB,_ui,32,_si,32,_si,32,"\n\txor\t%s%s"},
{_xorB,_si,32,_ui,32,_si,32,"\n\txor\t%s%s"},
{_xorB,_si,32,_si,32,_si,32,"\n\txor\t%s%s"},
{_shLft,_ui,32,_ui,32,_ui,32,"\n\tmov\tecx,%s\n\tshl\teax,cl"},
{_shLft,_ui,32,_si,32,_si,32,"\n\tmov\tecx,%s\n\tshl\teax,cl"},
{_shLft,_si,32,_ui,32,_ui,32,"\n\tmov\tecx,%s\n\tshl\teax,cl"},
{_shLft,_si,32,_si,32,_si,32,"\n\tmov\tecx,%s\n\tshl\teax,cl"},
{_shRgt,_ui,32,_ui,32,_ui,32,"\n\tmov\tecx,%s\n\tshr\teax,cl"},
{_shRgt,_ui,32,_si,32,_si,32,"\n\tmov\tecx,%s\n\tshr\teax,cl"},
{_shRgt,_si,32,_ui,32,_ui,32,"\n\tmov\tecx,%s\n\tshr\teax,cl"},
{_shRgt,_si,32,_si,32,_si,32,"\n\tmov\tecx,%s\n\tshr\teax,cl"},
{_or,_ui,32,_ui,32,_ui,32,"\n\tor\t%s%s"},
{_and,_ui,32,_ui,32,_ui,32,"\n\tand\t%s%s"},
{_ixbz,_ui+cdPtr,32,_ui,32,_ui,32,"\n\tmov\tesi,%s\n\tmov\tebx,%s\n\tmov\teax,[ebx][esi*4]"},
{_ixbz,_ui+cdPtr,32,_si,32,_ui,32,"\n\tmov\tesi,%s\n\tmov\tebx,%s\n\tmov\teax,[ebx][esi*4]"},
{_ixbz,_si+cdPtr,32,_ui,32,_si,32,"\n\tmov\tesi,%s\n\tmov\tebx,%s\n\tmov\teax,[ebx][esi*4]"},
{_ixbz,_si+cdPtr,32,_si,32,_si,32,"\n\tmov\tesi,%s\n\tmov\tebx,%s\n\tmov\teax,[ebx][esi*4]"},
{_ixbz,_f+cdPtr,32,_ui,32,_f,32,"\n\tmov\tesi,%s\n\tmov\tebx,%s\n\tfld\t[ebx][esi*4]"},
{_ixbz,_f+cdPtr,32,_si,32,_f,32,"\n\tmov\tesi,%s\n\tmov\tebx,%s\n\tfld\t[ebx][esi*4]"},
{_ixbz,_d+cdPtr,32,_ui,32,_d,64,"\n\tmov\tesi,%s\n\tmov\tebx,%s\n\tfld\t[ebx][esi*8]"},
{_ixbz,_d+cdPtr,32,_si,32,_d,64,"\n\tmov\tesi,%s\n\tmov\tebx,%s\n\tfld\t[ebx][esi*8]"},
{_ixbz,_ui+cdPtr+cdArr,32,_ui,32,_ui,32,"\n\tmov\tesi,%s\n\tmov\teax,%s[esi*4]"},
{_ixbz,_ui+cdPtr+cdArr,32,_si,32,_ui,32,"\n\tmov\tesi,%s\n\tmov\teax,%s[esi*4]"},
{_ixbz,_si+cdPtr+cdArr,32,_ui,32,_si,32,"\n\tmov\tesi,%s\n\tmov\teax,%s[esi*4]"},
{_ixbz,_si+cdPtr+cdArr,32,_si,32,_si,32,"\n\tmov\tesi,%s\n\tmov\teax,%s[esi*4]"},
{_ixbz,_f+cdPtr+cdArr,32,_ui,32,_f,32,"\n\tmov\tesi,%s\n\tfld\t%s[esi*4]"},
{_ixbz,_f+cdPtr+cdArr,32,_si,32,_f,32,"\n\tmov\tesi,%s\n\tfld\t%s[esi*4]"},
{_ixbz,_d+cdPtr+cdArr,32,_ui,32,_d,64,"\n\tmov\tesi,%s\n\tfld\t%s[esi*8]"},
{_ixbz,_d+cdPtr+cdArr,32,_si,32,_d,64,"\n\tmov\tesi,%s\n\tfld\t%s[esi*8]"},
{(enum tokType)(_asOr+_lVlu),_ui,32,_ui,32,_ui,32,"\n\tor\t%s,%s"},
{(enum tokType)(_asOr+_lVlu),_ui,32,_si,32,_ui,32,"\n\tor\t%s,%s"},
{(enum tokType)(_asOr+_lVlu),_si,32,_ui,32,_si,32,"\n\tor\t%s,%s"},
{(enum tokType)(_asOr+_lVlu),_si,32,_si,32,_si,32,"\n\tor\t%s,%s"},
{(enum tokType)(_asAnd+_lVlu),_ui,32,_ui,32,_ui,32,"\n\tand\t%s,%s"},
{(enum tokType)(_asAnd+_lVlu),_ui,32,_si,32,_ui,32,"\n\tand\t%s,%s"},
{(enum tokType)(_asAnd+_lVlu),_si,32,_ui,32,_si,32,"\n\tand\t%s,%s"},
{(enum tokType)(_asAnd+_lVlu),_si,32,_si,32,_si,32,"\n\tand\t%s,%s"},
{(enum tokType)(_asXor+_lVlu),_ui,32,_ui,32,_ui,32,"\n\txor\t%s,%s"},
{(enum tokType)(_asXor+_lVlu),_ui,32,_si,32,_ui,32,"\n\txor\t%s,%s"},
{(enum tokType)(_asXor+_lVlu),_si,32,_ui,32,_si,32,"\n\txor\t%s,%s"},
{(enum tokType)(_asXor+_lVlu),_si,32,_si,32,_si,32,"\n\txor\t%s,%s"},
{(enum tokType)(_asAdd+_lVlu),_ui,32,_ui,32,_ui,32,"\n\tadd\t%s,%s"},
{(enum tokType)(_asAdd+_lVlu),_ui,32,_si,32,_ui,32,"\n\tadd\t%s,%s"},
{(enum tokType)(_asAdd+_lVlu),_ui,32,_f,32,_ui,32,"\n\tfild\t%s\n\tfadd\t%s\n\tfistp\t%s"},
{(enum tokType)(_asAdd+_lVlu),_ui,32,_d,32,_ui,32,"\n\tfild\t%s\n\tfadd\t%s\n\tfistp\t%s"},
{(enum tokType)(_asAdd+_lVlu),_si,32,_ui,32,_si,32,"\n\tadd\t%s,%s"},
{(enum tokType)(_asAdd+_lVlu),_si,32,_si,32,_si,32,"\n\tadd\t%s,%s"},
{(enum tokType)(_asAdd+_lVlu),_si,32,_f,32,_si,32,"\n\tfild\t%s\n\tfadd\t%s\n\tfistp\t%s"},
{(enum tokType)(_asAdd+_lVlu),_si,32,_d,32,_si,32,"\n\tfild\t%s\n\tfadd\t%s\n\tfistp\t%s"},
{(enum tokType)(_asAdd+_lVlu),_f,32,_ui,32,_f,32,"\n\tfld\t%s\n\tfiadd\t%s\n\tfstp\t%s"},
{(enum tokType)(_asAdd+_lVlu),_f,32,_si,32,_f,32,"\n\tfld\t%s\n\tfiadd\t%s\n\tfstp\t%s"},
{(enum tokType)(_asAdd+_lVlu),_f,32,_f,32,_f,32,"\n\tfld\t%s\n\tfadd\t%s\n\tfstp\t%s"},
{(enum tokType)(_asAdd+_lVlu),_f,32,_d,64,_f,32,"\n\tfld\t%s\n\tfadd\t%s\n\tfstp\t%s"},
{(enum tokType)(_asAdd+_lVlu),_d,64,_ui,32,_d,32,"\n\tfld\t%s\n\tfiadd\t%s\n\tfstp\t%s"},
{(enum tokType)(_asAdd+_lVlu),_d,64,_si,32,_d,64,"\n\tfld\t%s\n\tfiadd\t%s\n\tfstp\t%s"},
{(enum tokType)(_asAdd+_lVlu),_d,64,_f,32,_d,64,"\n\tfld\t%s\n\tfadd\t%s\n\tfstp\t%s"},
{(enum tokType)(_asAdd+_lVlu),_d,64,_d,64,_d,64,"\n\tfld\t%s\n\tfadd\t%s\n\tfstp\t%s"},
{(enum tokType)(_asAdd+_lVlu),_ui+cdPtr,32,_ui,32,_ui+cdPtr,32,"\n\tmov\tedi,%s\n\tmov\tcl,2\n\tshl\teax,cl\n\tadd\t[edi],eax"},
{(enum tokType)(_asAdd+_lVlu),_ui+cdPtr,32,_si,32,_ui+cdPtr,32,"\n\tmov\tedi,%s\n\tmov\tcl,2\n\tshl\teax,cl\n\tadd\t[edi],eax"},
{(enum tokType)(_asAdd+_lVlu),_si+cdPtr,32,_ui,32,_si+cdPtr,32,"\n\tmov\tedi,%s\n\tmov\tcl,2\n\tshl\teax,cl\n\tadd\t[edi],eax"},
{(enum tokType)(_asAdd+_lVlu),_si+cdPtr,32,_si,32,_si+cdPtr,32,"\n\tmov\tedi,%s\n\tmov\tcl,2\n\tshl\teax,cl\n\tadd\t[edi],eax"},
{(enum tokType)(_asAdd+_lVlu),_f+cdPtr,32,_ui,32,_f+cdPtr,32,"\n\tmov\tedi,%s\n\tmov\tcl,2\n\tshl\teax,cl\n\tadd\t[edi],eax"},
{(enum tokType)(_asAdd+_lVlu),_f+cdPtr,32,_si,32,_f+cdPtr,32,"\n\tmov\tedi,%s\n\tmov\tcl,2\n\tshl\teax,cl\n\tadd\t[edi],eax"},
{(enum tokType)(_asAdd+_lVlu),_d+cdPtr,32,_ui,32,_d+cdPtr,32,"\n\tmov\tedi,%s\n\tmov\tcl,3\n\tshl\teax,cl\n\tadd\t[edi],eax"},
{(enum tokType)(_asAdd+_lVlu),_d+cdPtr,32,_si,32,_d+cdPtr,32,"\n\tmov\tedi,%s\n\tmov\tcl,3\n\tshl\teax,cl\n\tadd\t[edi],eax"},
{(enum tokType)(_ass+_lVlu),_ui,32,_ui,32,_ui,32,"\n\tmov\t%s,%s"},
{(enum tokType)(_ass+_lVlu),_ui,32,_si,32,_ui,32,"\n\tmov\t%s,%s"},
{(enum tokType)(_ass+_lVlu),_ui,32,_f,32,_ui,32,"\n\tfistp\t%s"},
{(enum tokType)(_ass+_lVlu),_ui,32,_d,32,_ui,32,"\n\tfistp\t%s"},
{(enum tokType)(_ass+_lVlu),_si,32,_ui,32,_si,32,"\n\tmov\t%s,%s"},
{(enum tokType)(_ass+_lVlu),_si,32,_si,32,_si,32,"\n\tmov\t%s,%s"},
{(enum tokType)(_ass+_lVlu),_si,32,_f,32,_si,32,"\n\tfistp\t%s"},
{(enum tokType)(_ass+_lVlu),_si,32,_d,32,_si,32,"\n\tfistp\t%s"},
{(enum tokType)(_ass+_lVlu),_f,32,_ui,32,_f,32,"\n\tfild\t[esp]\n\tfstp\t%s"},
{(enum tokType)(_ass+_lVlu),_f,32,_si,32,_f,32,"\n\tfild\t[esp]\n\tfstp\t%s"},
{(enum tokType)(_ass+_lVlu),_f,32,_f,32,_f,32,"\n\tfstp\t%s"},
{(enum tokType)(_ass+_lVlu),_f,32,_d,64,_f,32,"\n\tfstp\t%s"},
{(enum tokType)(_ass+_lVlu),_d,64,_ui,32,_d,64,"\n\tfstp\t%s"},
{(enum tokType)(_ass+_lVlu),_d,64,_si,32,_d,64,"n\tfstp%s"},
{(enum tokType)(_ass+_lVlu),_d,64,_f,32,_d,64,"\n\tfstp%s"},
{(enum tokType)(_ass+_lVlu),_d,64,_d,64,_d,64,"\n\tfstp%s"},
{(enum tokType)(_ixbz+_lVlu),_ui+cdPtr,32,_ui,32,_ui,32,"\n\tmov\tesi,%s\n\tmov\tebx,%s\n\tlea\tebx,[ebx][eax*4]"},
{(enum tokType)(_ixbz+_lVlu),_ui+cdPtr,32,_si,32,_ui,32,"\n\tmov\tesi,%s\n\tmov\tebx,%s\n\tlea\tebx,[ebx][esi*4]"},
{(enum tokType)(_ixbz+_lVlu),_si+cdPtr,32,_ui,32,_si,32,"\n\tmov\tesi,%s\n\tmov\tebx,%s\n\tlea\tebx,[ebx][esi*4]"},
{(enum tokType)(_ixbz+_lVlu),_si+cdPtr,32,_si,32,_si,32,"\n\tmov\tesi,%s\n\tmov\tebx,%s\n\tlea\tebx,[ebx][esi*4]"},
{(enum tokType)(_ixbz+_lVlu),_f+cdPtr,32,_ui,32,_f,32,"\n\tmov\tesi,%s\n\tmov\tebx,%s\n\tlea\tebx,[ebx][eax*4]"},
{(enum tokType)(_ixbz+_lVlu),_f+cdPtr,32,_si,32,_f,32,"\n\tmov\tesi,%s\n\tmov\tebx,%s\n\tlea\tebx,[ebx][esi*4]"},
{(enum tokType)(_ixbz+_lVlu),_d+cdPtr,32,_ui,32,_d,64,"\n\tmov\tesi,%s\n\tmov\tebx,%s\n\tlea\tebx,[ebx][esi*8]"},
{(enum tokType)(_ixbz+_lVlu),_d+cdPtr,32,_si,32,_d,64,"\n\tmov\tesi,%s\n\tmov\tebx,%s\n\tlea\tebx,[ebx][esi*8]"},
{(enum tokType)(_ixbz+_lVlu),_ui+cdPtr+cdArr,32,_ui,32,_ui,32,"\n\tmov\tesi,%s\n\tlea\tebx,%s[esi*4]"},
{(enum tokType)(_ixbz+_lVlu),_ui+cdPtr+cdArr,32,_si,32,_ui,32,"\n\tmov\tesi,%s\n\tlea\tebx,%s[esi*4]"},
{(enum tokType)(_ixbz+_lVlu),_si+cdPtr+cdArr,32,_ui,32,_si,32,"\n\tmov\tesi,%s\n\tlea\tebx,%s[esi*4]"},
{(enum tokType)(_ixbz+_lVlu),_si+cdPtr+cdArr,32,_si,32,_si,32,"\n\tmov\tesi,%s\n\tlea\tebx,%s[esi*4]"},
{(enum tokType)(_ixbz+_lVlu),_f+cdPtr+cdArr,32,_ui,32,_f,32,"\n\tmov\tesi,%s\n\tlea\tebx,%s[esi*4]"},
{(enum tokType)(_ixbz+_lVlu),_f+cdPtr+cdArr,32,_si,32,_f,32,"\n\tmov\tesi,%s\n\tlea\tebx,%s[esi*4]"},
{(enum tokType)(_ixbz+_lVlu),_d+cdPtr+cdArr,32,_ui,32,_d,64,"\n\tmov\tesi,%s\n\tlea\tebx,%s[esi*8]"},
{(enum tokType)(_ixbz+_lVlu),_d+cdPtr+cdArr,32,_si,32,_d,64,"\n\tmov\tesi,%s\n\tlea\tebx,%s[esi*8]"},
};
int lnCod[]=			// вектор довжин типів
{0, 0, 0, 0,
 8,16,32,64,
 8,16,32,64,//
 32,64,80,48,
 _lbl,//
 _enm,_str,_unn,
};
enum datType tpLx[]=	// масив кодів типів констант від типів лексем
{_v,	//0 Eu - Некласифікований об'єкт
 _v,	//1 S0 - Роздільник
 _v,	//2 S1g - Знак числової константи
 _ui,	//3 S1c - Ціле число
 _d,	//4 S2c - Число з точкою
 _v,	//5 S1e - Літера "e" або "E"
 _v,	//6 S1q - Знак "-" або "+"
 _f,	//7 S1p - Десяткові цифри порядку
 _v,	//8 S1n - Елементи імені
 _v,	//9 S1s - Літери рядка або символьної константи
 _v,	//10 S1t - Елементи констант, які перетворюються 
 _strn,	//11 S2s - Ознака закінчення константи
 _v,	//12 S2 - Початковий елемент групового роздільника
 _v,	//13 S3 - Наступний елемент групового роздільника
 _ui,	//14?S3c - Ціле число з недесятковою основою
 _v,	//15?S0p - Ознака типу константи
 _v,	//16 Soc- Вісімковий код
 _v,	//17 Scr- Коментар-рядок
 _v,	//18 Scl- Обмежений коментар
 _v,	//19 Ec - Неправильна константа
 _v,	//20 Ep - Неправильна константа з точкою
 _v,	// Eq - Неправильна константа з порядком
 _v,	// En - Неправильне ім'я
 _v	// Eo - Неприпустиме сполучення операцій
};
struct recrdTMD tpLxMd[]=	
// масив кодів та ознак ключових слів типів
{{_v, 0, 0},	//0 _void
 {_v, 0, 0},	//1 _extern
 {_v, 0, 0},	//2 _var
 {_v,cdCns,0},	//3 _const
 {_enm, 0,32},	//4 _enum
 {_str, 0, 0},	//5 _struct/*_record*/
 {_unn, 0, 0},	//6 _union
 {_v,cdReg,0},	//7 _register
 {_ui,0,32},	//8 _unsigned
 {_si,0,32},	//9 _signed
 {_si,0, 8},	//10 _char
 {_si,0,16},	//11 _short 
 {_si,0,32},	//12 _int 
 {_si,0,32},	//13 _long 
 {_si,0,64},	//14 _sint64
 {_ui,0,64},	//15 _uint64
 {_f, 0,32},	//16 _float
 {_d, 0,64},	//17 _double 
};
struct recrdTPD	tpTbl[]=	// таблиця модифікованих типів
{{{_void,_void,_void},_v,0},
{{_enum,_void,_void},_enm,32},
{{_struct,_void,_void},_str,0},
{{_union,_void,_void},_unn,0},
{{_unsigned,_void,_void},_ui,32},
{{_signed,_void,_void},_si,32},
{{_char,_unsigned,_void},_uc,8},
{{_char,_signed,_void},_sc,8},//4
{{_char,_void,_void},_sc,8},
{{_short,_void,_void},_si,16},
{{_short,_unsigned,_void},_ui,16},
{{_short,_signed,_void},_si,16},
{{_int,_void,_void},_si,32},//9
{{_int,_unsigned,_void},_ui,32},
{{_int,_signed,_void},_si,32},
{{_int,_long,_void},_si,32},
{{_long,_void,_void},_si,32},
{{_float,_void,_void},_f,32},//14
{{_double,_void,_void},_d,64},
{{_double,_long,_void},_ld,80},
{{_class,_void,_void},_cls,0},
};