//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Kurs.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_KURSTYPE                    129
#define IDR_MENU1                       130
#define IDD_CHANGEVAL                   131
#define IDD_DIALOG1                     132
#define IDC_EDIT1                       1000
#define IDC_LIST1                       1001
#define IDC_EDIT2                       1002
#define IDC_SPIN1                       1003
#define IDC_BUTTON1                     1004
#define ID_PROPERT                      32771
#define ID_ADD_TASK                     32772
#define ID_ADD_RELATION                 32773
#define ID_DEL_TASK                     32774
#define ID_DEL_RELATION                 32775
#define ID_REPAINT                      32777
#define ID_ADD_TASKM                    32778
#define ID_VIEW_PROC                    32782
#define ID_VIEW_GRAPHS                  32784
#define ID_CPU                          32787
#define ID_EVALUATE                     32788
#define ID_FAULT                        32789
#define ID_STATE_NORM                   32790
#define ID_STATE_TRACE                  32791
#define ID_STATE_MANUAL                 32792
#define ID_STEP                         32793

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        133
#define _APS_NEXT_COMMAND_VALUE         32794
#define _APS_NEXT_CONTROL_VALUE         1005
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
