import os,time
s = os.stat(r"file.txt")
print("{0:20}     {1:7}".format("Атрибути файлу:", "file.txt" ))
print(s)
print("------------------------------------------------------")

print("{0:<30} {1:<20}".format("Розмір файлу file.txt:",s.st_size ))
tc=time.strftime("%d.%m.%Y %H:%M:%S", time.localtime(s.st_ctime))
print("{0:<30} {1:<20}".format("Час створення file.txt:",tc ))
ta=time.strftime("%d.%m.%Y %H:%M:%S", time.localtime(s.st_atime))
print("{0:<30} {1:<20}".format("Час доступу file.txt:",ta ))
tm=time.strftime("%d.%m.%Y %H:%M:%S", time.localtime(s.st_mtime))
print("{0:<30} {1:<20}".format("Час модифікації file.txt:",tm ))
print("------------------------------------------------------")
print("{0:<40} {1:<20}".format("Тип файлу та режим доступу:",s.st_mode ))
print("{0:<40} {1:<20}".format("Номер файлу в структурі Айнод:",s.st_ino ))
print("{0:<40} {1:<20}".format("Ідентифікатор приладу зберігання файлу:",s.st_dev ))
print("{0:<40} {1:<20}".format("Місце файлу на диску:",s.st_nlink ))
print("{0:<40} {1:<20}".format("Ідентифікатор користувача:",s.st_uid ))
print("{0:<40} {1:<20}".format("Ідентифікатор групи користувача:",s.st_gid ))
print("------------------------------------------------------")
