import os,time
s=os.stat(r"file.txt")
print("{0:20}     {1:7}".format("Атрибути файлу:", "file.txt" ))
print(s)
print("------------------------------------------------------")
ta=time.strftime("%d.%m.%Y %H:%M:%S", time.localtime(s.st_atime))
print("{0:<30} {1:<20}".format("Час доступу file.txt:",ta ))
tm=time.strftime("%d.%m.%Y %H:%M:%S", time.localtime(s.st_mtime))
print("{0:<30} {1:<20}".format("Час модифікації file.txt:",tm ))
print("------------------------------------------------------")
os.utime(r"file.txt", None)
s=os.stat(r"file.txt")
print("{0:20}     {1:7}".format("Встановлення поточного часу ", "file.txt" ))
print(s)
print("------------------------------------------------------")
ta=time.strftime("%d.%m.%Y %H:%M:%S", time.localtime(s.st_atime))
print("{0:<30} {1:<20}".format("Час доступу file.txt:",ta ))
tm=time.strftime("%d.%m.%Y %H:%M:%S", time.localtime(s.st_mtime))
print("{0:<30} {1:<20}".format("Час модифікації file.txt:",tm ))
print("------------------------------------------------------")

t = time.time() - 600
os.utime(r"file.txt", (t, t))
s=os.stat(r"file.txt")
print("{0:20}     {1:7}".format("Встановити -600сек:", "file.txt" ))
print(s)
print("------------------------------------------------------")
ta=time.strftime("%d.%m.%Y %H:%M:%S", time.localtime(s.st_atime))
print("{0:<30} {1:<20}".format("Час доступу file.txt:",ta ))
tm=time.strftime("%d.%m.%Y %H:%M:%S", time.localtime(s.st_mtime))
print("{0:<30} {1:<20}".format("Час модифікації file.txt:",tm ))
print("------------------------------------------------------")


