from tkinter import *
root=Tk()
button1 = Button(text="1", font = ("Arial", 20))
button2 = Button(text="2", font = ("Arial", 20))
button3 = Button(text="3", font = ("Arial", 20))
button4 = Button(text="4", font = ("Arial", 20))
button1.pack(side='top')
button2.pack(side='bottom')
button3.pack(side='left')
button4.pack(side='right')
root.mainloop()
