D0= not x1*x2* not x3* not x4* not Q0*Q1* not Q2 V x1*x2*x3*x4* not Q0*Q1* not Q2 V x1*x2*x3*x4*Q0* not Q1* not Q2 V x1* not x2*x3*x4*Q0* not Q1*Q2
D1=x1*x2*x3*x4* not Q0* not Q1*Q2 V x1*x2*x3*x4* not Q0*Q1* not Q2 V x1*x2*x3*x4*Q0* not Q1*Q2
D2=x1*x2*x3*x4* not Q0* not Q1* not Q2 V  not x1*x2* not x3* not x4* not Q0*Q1* not Q2 V x1*x2*x3*x4* not Q0*Q1* not Q2 V x1*x2*x3*x4*Q0* not Q1* not Q2 V x1*x2*x3*x4*Q0* not Q1*Q2
y1= not Q0* not Q1*Q2
y2= not Q0*Q1* not Q2
y3= not Q0*Q1*Q2
y4=Q0* not Q1* not Q2
y5=Q0* not Q1*Q2
